### ISSUE TITLE
Requesting support for nuttcp udp burst mode (arg -Ri)

### ISSUE THREAD

**Issue by chris-konger** [perfsonar/pscheduler#1004]
It appears pscheduler does not currently support use of nuttcp's udp burst mode (the -Ri flag). While one CAN run nuttcp from the command-line, doing so can interfere/overlap with scheduled tests.

Mark Feit thought the addition of a new flag/param (he suggested "--bandwith-strict") would allow for the passing of test arguments exactly as given ...

pscheduler --bandwidth-strict="2g/20"  -> nuttcp -Ri2g/20

Thanks for considering this new feature request ... much appreciated!

Chris Konger / NOAA N-Wave

**Comment by mfeit-internet2** [comment]
My intent was for the `bandwidth-strict` parameter to be a boolean that says "never exceed the specified bandwidth ever" and would trigger the use of `-Ri` instead of `-R`.

The `2g/20` syntax isn't described in the documentation.  I had to dig through the code to find what it was and still don't have a good bead on what it means.  If there's a reason to support that or something like it, I can re-think this to incorporate it.  The usual approach for these things is to come up with something generally-useful and not turn the parameters into proxies for a specific tool's command-line switches.

**Comment by chris-konger** [comment]
I thought the Cumulus Networks man pages were more useful than the 
official man page ... it is mentioned briefly there ... and even the 
official ESnet nuttcp pages show examples of how it can be used to find 
small buffer switches etc. But looking at the source code is probably 
even better!

The param in front of the slash is the desired bandwidth ... the param 
after the slash is the number of packets within a single burst.

ESnet page showing nuttcp usage to find small buffers ...
https://fasterdata.es.net/performance-testing/network-troubleshooting-tools/nuttcp/

Cumulus Networks examples of nuttcp udp burst mode ...
https://support.cumulusnetworks.com/hc/en-us/articles/216509388-Throughput-Testing-and-Troubleshooting#udp_burst_mode

Chris Konger
Sr Network Engineer - Cloud (Contractor)

NOAA
Mail stop: N-Wave
325 Broadway
Boulder, CO 80305
Phone: 303-497-7125
Cell: 720.650.9801

**Comment by chris-konger** [comment]
A general purpose alternative would be a new param would take a string 
such as --extra-args="blah" where you could pass other args to the 
underlying tool.

The downside to that approach is the general mischief potential of 
passing stuff through without examination.  ;)

Chris Konger
Sr Network Engineer - Cloud (Contractor)

NOAA
Mail stop: N-Wave
325 Broadway
Boulder, CO 80305
Phone: 303-497-7125
Cell: 720.650.9801

**Comment by mfeit-internet2** [comment]
> The param in front of the slash is the desired bandwidth ... the param
after the slash is the number of packets within a single burst.

It sounds like we need two new test parameters:

 * `bandwidth-strict` - Boolean that means the value in the `bandwidth` parameter should never be exceeded.  In the nuttcp tool, this will trigger the use of `-Ri` instead of just `-R`.
 * `packets-per-burst` - Positive integer.  Does what it says, will require that a `bandwidth` be specified and implies `bandwidth-strict`.

 > The downside to that approach is the general mischief potential of
passing stuff through without examination.  ;)

Which is the other reason why that won't be happening.  :-)  Really, though, I don't have a problem with expanding the tests to support new things.  The MVP for pScheduler at first release was to be able to do everything BWCTL could.  This new stuff is gravy and not difficult.

**Comment by mfeit-internet2** [comment]
For a sanity check, this is how bandwidth-related test parameters will translate to nuttcp bandwidth controls:

|Test Parameters|Nuttcp Bandwidth Switch|
|----------------|--------------------------|
|`--bandwidth 1G`|`-R1000000.0`| 
|`--bandwidth 1G --bandwidth-strict`|`-Ri1000000.0`| 
|`--bandwidth 1G --bandwidth-strict --burst-size 20`|`-Ri1000000.0/20`|
|`--bandwidth-strict`|`-Ri0.0`| 
|`--bandwidth-strict --burst-size 20`|`-Ri0.0/20`|
|`--burst-size 20`|`-Ri0.0/20`| 

If you're okay with that, I'll merge it into 4.3.
