### ISSUE TITLE
Check WSGI Processes/Threads

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#105]
Check to make sure we're not going to have any issued with mod_wsgi's threads and some of the shared, per-process resources like the logger and especially the database handles.

Tune mod_wsgi appropriately.

**Comment by arlake228** [comment]
Having some experience with this in esmond, you may actually want to down that thread count a bit. Its a bit counter-intuitive, but due to python's global interpreter lock you may actually end up slowing down performance by having two many threads competing for locked bytecode. We actually experienced this in esmond and got a pretty significant bump dropping the thread count down in favor of more processes. We use 10 processes and 5 threads over there FWIW.

**Comment by mfeit-internet2** [comment]
I'm of mixed mind about what to do with that.  We do have a lot of long-running requests where the WSGI app runs an outside process and waits for it or is doing a database query that does.  Most of those won't need to grab the GIL while they're waiting, and I don't want to go too big on processes lest we chew up a lot of memory on low-resource systems.

I think some of the instability Dan and I saw this afternoon may have been related to some of the database bits not being thread-safe, because even after the adjustment, I still saw a bit of it.  I'll be looking into this tomorrow instead of later.

**Comment by mfeit-internet2** [comment]
Turned out this needed to be investigated sooner rather than later.  All fixed.

**Comment by mfeit-internet2** [comment]
Reopening.  Turns out we need to do one connection per thread or everything gets serialized.

**Comment by mfeit-internet2** [comment]
This was taken care of by db7d8118cdaf4a464a44df81af58ba93a86e6a22.
