### ISSUE TITLE
--congestion option not allowing the right set of congestion control algorithms

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#1075]
I'm getting this error:

>pscheduler task throughput --congestion bbr2 --client-cpu-affinity=1 --dest bois-pt1
Submitting task...
Unable to determine the lead participant: At /congestion: u'bbr2' is not one of ['reno', 'cubic', 'bic', 'htcp', 'vegas', 'westwood', 'yeah', 'bbr']

But here are the available congestion control algorithms on my host:
>sysctl net.ipv4.tcp_available_congestion_control
net.ipv4.tcp_available_congestion_control = reno cubic bbr2 htcp

It looks like pscheduler has a hard coded list of congestion control options, but it should really get the set from sysctl.

(Yes, I know this might tricky for a 3rd party transfer....)

**Comment by mfeit-internet2** [comment]
> (Yes, I know this might tricky for a 3rd party transfer....)

Yep, that's a hairy one, and I can argue both sides:

 * If we allow an arbitrary string, someone who fat-fingers `bbt` instead of `bbr` will have their test accepted, only to have it fail and leave them scratching their head over why squares on their dashboard have gone orange.

 * If we restrict it to a known set, we can give a thumbs up or down immediately and we know that the algorithm will work if the system supports it.  That still has the go-orange problem if the system doesn't support it, but less so.

I will bring the list up to date with what's in Linux 5.9, which is:
```
bbr
bic
bpf
cdg
cubic
dctcp
highspeed
htcp
hybla
illinois
lp
nv
scalable
vegas
veno
westwood
yeah
```

I'd like to further propose that, for people running experimental congestion control that's not in the mainstream kernel, we adopt an `x-` prefix, which would say that anything after the hyphen will be passed through to the tool unvalidated (e.g., `x-foo` would be passed to iperf3 as `--congestion foo`).  Would that work for you?

I can add this to 4.3 since we're not at code freeze yet and it's a low-risk change.

**Comment by bltierney** [comment]
x- would work, but I'd still prefer if source = localhost to get if from sysctl.

**Comment by arlake228** [comment]
I think it would be good to add bbr2 (or x-bbr2) to the list if we are
gonna updated for 4.3. That’s going to be a really common one people in our
community will want to test.


On October 14, 2020 at 2:09:43 PM, Brian Tierney (notifications@github.com)
wrote:

x- would work, but I'd still prefer if source = localhost to get if from
sysctl.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/pscheduler/issues/1075#issuecomment-708571921>,
or unsubscribe

**Comment by mfeit-internet2** [comment]
> I'd still prefer if source = localhost to get if from sysctl.

The test specs should pass or fail validation in a vacuum and not depend on the state of the system doing the validation or whether or not it's happening on the same host running it.  We did an ugly hack like that for BWCTL backward compatibility that was nuked from orbit at the earliest opportunity.  Keeping tests system-independent will become an important factor when we start pushing the structure of test specifications and information to the plugins' enumerations, which is something we're planning.

If a test is scheduled and the CC module it specified is unloaded before run time, what would have been accepted as valid becomes invalid.  Getting around that would make a good case for not validating the CC algorithm at all beyond making sure it isn't an empty string.  I could be persuaded to do that and let the tests fail where they may on the grounds that futzing with CC is something of an expert-level feature.

I'm going to hold off on this until we've come up with a concrete plan.

**Comment by bltierney** [comment]
It would be very helpful for my current testing if you could just add bbr2 to the list of hardcoded CC options. Thanks.

**Comment by mfeit-internet2** [comment]
Here's where I landed:

 * Starting in 4.3.0, the congestion control value will still be validated, but only to the extent that it must be a non-empty string.
 * Any value not in the old hard-coded list (`"bbr", "bic", "cubic", "htcp",  "reno", "vegas", "westwood", "yeah"`) will require that the test spec's `schema` be `4` or later since only those in the list will validate with schemas `3` and earlier.  Values in the list will leave the schema as whatever it would have been otherwise.
 * If you use a value not in the list (e.g.,`bbr2`), systems earlier than 4.3 will decline to participate in throughput tests because they don't support schema 4.  I know that congestion control is a client-side option, but the test spec has to validate at both ends.

This change will appear in the staging code next time we build it.

If you're testing from an expendable system, I can give you a quick patch to the production code that will make whichever tool you're using use `bbr2` when you specify one of the other values in the list.  (That would be supplied with your famous "you break it, you own both pieces" guarantee.)

**Comment by mfeit-internet2** [comment]
**Release Notes:**

The throughput test will now accept any congestion control algorithm; runs will fail if the specified algorithm is not available on the system.

(@arlake228:  These need to be added to the 4.3.0 notes.)
