### ISSUE TITLE
ModuleNotFoundError: No module named 'pscheduler'

### ISSUE THREAD

**Issue by ozej8y** [perfsonar/pscheduler#1130]
Hi All,

I'm new to perfsonar, but have been having a few issues with it.

I have installed perfsonar-toolkit 4.3.3-1.el7 onto Centos 7.9 using yum by following the setup instructions.

I'm seeing the following error with regards to the pscheduler functionality.

```
$ pscheduler troubleshoot
Performing basic troubleshooting of localhost.

localhost:

  Measuring MTU... 65535 (Local)
  Looking for pScheduler... OK.
  Fetching API level... 4
  Checking clock... OK.
  Exercising API... Status... Tests... Tools... OK.
  Fetching service status... OK.
  Checking services... ticker... scheduler... runner... archiver... OK.
  Idle test... Failed.

Unable to post task: Unable to validate test spec: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/classes/test/idle/spec-is-valid", line 6, in <module>
    import pscheduler
ModuleNotFoundError: No module named 'pscheduler'
```

After looking at the python code for 'troubleshoot' it actually imports the pscheduler module and runs, but some of the other python modules have trouble with 'import pscheduler'.

This issue is preventing me from scheduling tests as the logging is full of this error.

Any help to fix this is greatly appreciated.

Thanks,
               Jay.

**Comment by mfeit-internet2** [comment]
What you're seeing is a program launched by the pScheduler API not being able to load the module.  The difference between that and `troubleshoot` is that programs run by the API happen in whatever environment the Apache web server gives it.

The arrangements for the way we configure Apache haven't undergone any meaningful change in three years, and we're not seeing this on other systems.  Is there anything about the way your system is configured that's different than out-of-the box CentOS 7, especially as Apache is concerned?

**Comment by mfeit-internet2** [comment]
Certbot should be fine; if you can talk to the API at all, that's not getting in the way.

Both `troubleshoot` and the REST API make extensive use of the `pscheduler` module.  The first seven steps in the troubleshooting process exercise both sides, which is good confirmation that it's installed and working.

Try this:

```
$ /usr/libexec/pscheduler/classes/test/idle/spec-is-valid < /dev/null
{"valid": false, "error": "Invalid JSON: Expecting value: line 1 column 1 (char 0)"}
```

If you get the `ModuleNotFoundError`, there's a problem with the way your system is configured and the web server is probably fine.  Try a few others by substituting other test types (`throughput`, `rtt`, etc.) for `idle` in the path to the program.

If you get the expected output (which is an error message and just fine because you can't read valid JSON out of `/dev/null`), something's not configured the same way as the toolkit we ship.  My suspicion would be that something in Apache is configured to jail external programs in a way that they can't see the Python library or SELinux is configured to break it.

Your system is the first I can recall in the four years since pScheduler was released to show this behavior.  We have had several instances where someone said they were installing on CentOS and later found that there were some site-specific changes made that caused problems.  I'd look into those, too.

**Comment by ozej8y** [comment]
Thanks for the additional information.
We are investigating how the system is configured to address this.

**Comment by mfeit-internet2** [comment]
Do let us know what you find out.
