### ISSUE TITLE
http-queue filling up after 4.4.0 upgrade

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/pscheduler#1174]
The PMP hosts we manage at GÉANT have seen an increase of a few tens to hundreds of entries in the `http_queue`.  It seems all the items in the queue are remote tasks that should get deleted but that receive a 403 error when trying to do the deletion.

**Comment by mfeit-internet2** [comment]
Notes:

Looks like it's all `DELETE` (cancel) operations that involve keys and the far end returning `403` (Forbidden).  These hosts are involved:

 * psmp-gn-mgmt-lon-uk.geant.org
 *  psmp-gn-mgmt-01-lis-pt.geant.net
 *  psmp-gn-bw-01-gen-ch.geant.net
 *  psmp-gn-bw-01-sof-bg.geant.net
 *  psmp-gn-bw-01-poz-pl.geant.net
 *  psmp-gn-mgmt-01-poz-pl.geant.net

I suspect these systems may be 4.3.x and don't behave as nicely with keys as 4.4 does.

Sent Antoine and Ivan this script to be run on one of those systems to pull the necessary data:
```
#!/bin/sh
#
# Pull information relavant to HTTP queue backlog
#
# Run as root on any of the following hosts:
#
#  psmp-gn-mgmt-lon-uk.geant.org
#  psmp-gn-mgmt-01-lis-pt.geant.net
#  psmp-gn-bw-01-gen-ch.geant.net
#  psmp-gn-bw-01-sof-bg.geant.net
#  psmp-gn-bw-01-poz-pl.geant.net
#  psmp-gn-mgmt-01-poz-pl.geant.net
#


line()
{
    echo '------------------------------------------------------------'
}

header()
{
    echo
    echo
    line
    echo "$@" | tr a-z A-Z
    line
    echo
}



hostname
date


header Installed Packages
pscheduler version

header Data From Database
postgresql-load <<EOF | sed -e 's/^-\[.*$/\n\n/'
\c pscheduler

\x

SELECT
    uuid,
    participant,
    json #>> '{_key}' AS key,
    participant_key,
    participants,
    json
FROM
    task
WHERE
    nparticipants > 1
    AND participants @> '"psmall-poz1.man.poznan.pl"'::JSONB
;
EOF
```

**Comment by mfeit-internet2** [comment]
@igarny was unable to run the script on the production systems because he had no root access but did confirm that all of them are < 4.4.0.

Absent positive confirmation based on the data, here's what I believe is happening:

Starting in 4.4.0, the lead in multi-participant tasks generates a key that's used with the other participant(s) if one wasn't provided to the lead.  This prevents cancellation of those tasks by third parties.

When the task is canceled at the lead (e.g., by pSConfig), the lead uses the key to cancel the other participants' counterparts.

Prior to 4.4.0, key handling was buggy and often resulted in a 403 (Forbidden) when a remote host tried to do a write operation to a task.

4.4.0 systems leading tasks that involve earlier systems will put `DELETE` operations into the HTTP queue that cause 4.3.x systems to reject them because of the bugs.  Those will pile up as they're retried and will eventually expire.

Upgrading the 4.3.x systems to 4.4 will fix the problem.

**Comment by mfeit-internet2** [comment]
If this is resolved, please close it.

**Comment by mfeit-internet2** [comment]
Assuming resolved.  Closing.
