### ISSUE TITLE
DNS plugin times out when the first DNS resolver is unavailable

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#1245]
When the first one of the DNS resolvers from `/etc/resolv.conf` is unavailable, the pScheduler DNS plugin doesn't seem to be able to use any other working one.  Running a task always results in a timeout.  Changing the order of resolvers in `/etc/resolv.conf` makes the DNS tasks work again.

Will https://github.com/perfsonar/pscheduler/issues/855 solve this behaviour?

**Comment by mfeit-internet2** [comment]
The changes in 855 won't affect this.

The `dnspy` plugin relies on DNSPython, which has its own implementation of the resolver.  I looked at the source, and it appears to follow the algorithm described in `resolv.conf(5)`:
 
```
       nameserver Name server IP address
              Internet address of a name server that the resolver should
              query, either an IPv4 address (in dot notation), or an
              IPv6 address in colon (and possibly dot) notation as per
              RFC 2373.  Up to MAXNS (currently 3, see <resolv.h>) name
              servers may be listed, one per keyword.  If there are
              multiple servers, the resolver library queries them in the
              order listed.  If no nameserver entries are present, the
              default is to use the name server on the local machine.
              (The algorithm used is to try a name server, and if the
              query times out, try the next, until out of name servers,
              then repeat trying all the name servers until a maximum
              number of retries are made.)
```

Note that some applications will query all of the nameservers in parallel, which is _not_ what you want here.  If the first server fails, there will be a marked increase in response time as it times out and tries the second.

The code, which is still as it was first written, configured DNSPython's per-server `timeout` and full-query `lifetime` to the same values, which causes the (undesired) side effect of only ever querying a single server.  So that needs to be fixed.

I think the right solution is to make the test's `timeout` parameter govern the full-query lifetime and split that evenly among the number of servers `resolv.conf` is configured to use, which we can't know until run time.

**Comment by tonin** [comment]
> I think the right solution is to make the test's timeout parameter govern the full-query lifetime and split that evenly among the number of servers resolv.conf is configured to use, which we can't know until run time.

Sounds good to me @mfeit-internet2

**Comment by mfeit-internet2** [comment]
**Release Notes:**

If no `nameserver` parameter is supplied in a `dns` test, the `dnspy` tool divides the length of the `timeout` parameter evenly among the number of resolvers configured on the system.  **This is a behavior change from earlier versions.**
