### ISSUE TITLE
update the iperf2 build

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#1317]
Hi Mark,
As per your suggestion I open the ticket here.

Here is the source repository for iperf2: https://sourceforge.net/p/iperf2/code/ci/master/tree/ 

Latest stable difficult to point at 2.1.9

Proposed procedure for Install: https://sourceforge.net/p/iperf2/code/ci/master/tree/INSTALL

Installation issue with 2.0.14 for Ubuntu20 (resolved): https://sourceforge.net/p/iperf2/tickets/61/

**Comment by tonin** [comment]
It's not clear what is released in the 2.1.x source tree, but there is some code at https://sourceforge.net/p/iperf2/code/ci/2-1-8/tree/

**Comment by tonin** [comment]
But what we can add is that having a more recent version of iperf2 is of interest because iperf2 supports the new Responsiveness metric (RPM) currently being drafted at IETF: https://github.com/network-quality/draft-ietf-ippm-responsiveness

Of course, for it to be useful for perfSONAR, we would also need pScheduler to make this new metric available to the users.  That is with the `--bounceback` option if I understand correctly.

**Comment by mfeit-internet2** [comment]
Adding yesterday's conversation with Tim Chown for posterity:

Tim Chown
  [7:45 AM](https://perfsonar.slack.com/archives/DRA69PV5H/p1675341932976199)
Hi Mark, Ivan said you’d be receptive to wrapping the latest version of iperf2 into perfSONAR, which would be great.  It does seem to be under quite active development.  My query came from a very interesting new type of response-time based test being worked on in the IETF which will be in iperf 2.1.9 (nt sure when that will be released but will ask) and having it available from any perfSONAR MP would be very useful.   I’m sure there’s amny other new iperf2 features we could benefit from as well since the stock version that ships with Linux.   Anyway, if you have any questions Simon Leinen and I join the IETF group calls.  Rob McMahon was in the last one too.
[7:47](https://perfsonar.slack.com/archives/DRA69PV5H/p1675342076411589)
aha, on 2.1.9 - “I’ll be creating a 2-1-9 release candidate branch soon. After that, we’ll put it through our internal testing & release cycle which takes about one month.”
[7:48](https://perfsonar.slack.com/archives/DRA69PV5H/p1675342135618139)
and the IETF draft - https://github.com/network-quality/draft-ietf-ippm-responsiveness
network-quality/draft-ietf-ippm-responsiveness
Stars
15
Language
HTML
Added by [GitHub](https://perfsonar.slack.com/services/B022FATAC8K)
[7:49](https://perfsonar.slack.com/archives/DRA69PV5H/p1675342162329699)
(and yeah, RPM isn’t the best name for this given the other uses of the acronym!)


Mark Feit
  [8:05 AM](https://perfsonar.slack.com/archives/DRA69PV5H/p1675343125043439)
We discussed that a bit during yesterday's dev call.  We already have a build of the older version in the distribution, so the new one should be close to plug and chug.    I would prefer to not put the new version into a production release until it's released, has seen some good exercise outside of perfSONAR and we've had a chance to make sure it won't break the existing plugin.
[8:06](https://perfsonar.slack.com/archives/DRA69PV5H/p1675343206656739)
If the IETF ratifies the responsiveness standard and iperf2 or other tools can test it, a new test plugin could be developed and we could add code to the iperf2 plugin to run it or just write a new plugin.


Tim Chown
  [8:23 AM](https://perfsonar.slack.com/archives/DRA69PV5H/p1675344216705639)
ok, thanks Mark.  not heard ‘plug and chug’ before :slightly_smiling_face:.  I agree on waiting until 2.1.9 is properly released.  I’ll find out more about how the test is integrated into iperf2, or whether there’s standalone implementations.  It’s something they’re hoping gets into residential CPEs, and Stuart Cheshire of Apple is the author of the original proposal.  SamKnows has also joined, and of course OpenWrt is there.


Mark Feit
  [8:24 AM](https://perfsonar.slack.com/archives/DRA69PV5H/p1675344279783629)
I'm pretty sure I heard P&C from an Englishman.  Several, actually.  Enough that I thought it was idiomatic over there.  :slightly_smiling_face:
[8:26](https://perfsonar.slack.com/archives/DRA69PV5H/p1675344382839669)
I'll need to understand the test a bit better before I can pontificate on the implications for pScheduler.  But do look us up after it germinates.
:+1:
1

**Comment by mfeit-internet2** [comment]
I'm going to treat this ticket as being for the upgrade and will start a new one for the responsiveness testing.

**Comment by laeti-tia** [comment]
Hello @mfeit-internet2 on which Debian or Ubuntu variant have you tested the Debian build?  It doesn't build on D10 which is our default build host for our Debian packages.  Maybe it will need different options for the different OS we support.

**Comment by mfeit-internet2** [comment]
I didn't test on D10 since we're not supporting it it 5.1.

I _think_ I tested it on at least D11, but I'd have to to re-test it.

**Comment by laeti-tia** [comment]
Good catch! Our build infrastructure still relies on D10 at the moment, I'll move it to U20 which is the lowest distro we will support with 5.1.  And U20 also requires the change introduced in 94ecb1398dff9eb0439d7bf084c7ee01e2179044

**Comment by laeti-tia** [comment]
Seems to now be fine.
