### ISSUE TITLE
Ubuntu 20: Postgres update cause all pscheduler tasks to start failing 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#1352]
A recent postgres auto-update seemed to take out all the ESnet perfSONAR hosts. It also seemed to take out my random GCP VM, so I think its pretty ubiquitous to Ubuntu 20. I dont have much details beyond that around the time of the update everything becomes non-starters. Restarting the daemon seems to enable pscheduler to retry things, though some of the servers were still being finicky so I had to run pscheduler internal reset

**Comment by robertkley** [comment]
The same thing happened to me with a fresh install of perfsonar-toolkit in Ubuntu 20. Basically, the issue was the following:
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  2249: Failed to archive https://perfsonar/pscheduler>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  <html><head>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  <title>503 Service Unavailable</title>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  </head><body>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  <h1>Service Unavailable</h1>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  <p>The server is temporarily unable to service your
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  request due to maintenance downtime or capacity
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  problems. Please try again later.</p>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  </body></html>
Aug 25 09:01:41 perfsonar python3[748720]: archiver WARNING  2249: Gave up archiving https://perfsonar/pscheduler>
I have just purged the database as you have done. Hopefully this will sort out the issue.

**Comment by mfeit-internet2** [comment]
This was fixed in #1373.
