### ISSUE TITLE
missleading error message for iperf2 test

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#1358]
This works fine:
   pscheduler task --tool iperf2  throughput  --dest hostname

But this gives an error:
    pscheduler task --tool iperf2  throughput   --mss 4096 --dest hostname
  Failed to post task: Unable to complete request: No tool in common among the participants: 

That error message is very misleading. I'm guessing the iperf2 arg parsing code does not include -M ?

Also, iperf2 supports -mss same as iperf3 with the same "-M" flag, so the no reason the test should fail.

**Comment by mfeit-internet2** [comment]
The message might be unclear, but it isn't misleading.  It means that none of the tool plugins on any of the hosts involved said they could run the test as specified.

Whoever wrote the iperf2 plugin didn't make it understand the `mss` parameter, either because uperf2 didn't support it at the time or because of an oversight.

I'll put this in the pipeline for 5.1.

**Comment by bltierney** [comment]
to me a better error message for this situation would be:
Failed to post task: Unable to complete request: No tool in common among the participants, or tool args not supported

**Comment by mfeit-internet2** [comment]
#384 fixes this.
