### ISSUE TITLE
ability to specify core/socket in NUMA hosts

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#166]
In order to get consistent results on 40/100G hosts with 2 CPU sockets, its essential that all throughput tests run on the same CPU socket (and the CPU socket that is the NIC is directly attached to.

Clients will have no idea which CPU this is, so this must be set in a server config file.

In bwctl, this was set using: test_cpu_affinity in /etc/bwctl-server/bwctl-server.conf  

But default, this should probably be  set to the CPU found by doing this:
     cat /sys/class/net/ethN/device/numa_node

**Comment by mfeit-internet2** [comment]
Comments:
* This is tool-specific since not all tools support it.
*  Since proper affinity can be determined programmatically, the tool should determine what interface will be used and set the options accordingly.  This should probably be done for all tests regardless of bandwidth.

Also assigning this to Dan since throughput is his baby.

**Comment by arlake228** [comment]
Dan added this in 09d2aa1a1e9f741d03a1b09e3b654fdb6a87eb65. Also its a library call so any future stuff should be able to do the same.
