### ISSUE TITLE
BUG: /etc/pscheduler/default-archives missing conf file

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#176]
Hi Mark, guys

On a full toolkit deployment I have found this file: /usr/share/pscheduler/psc-archiver-esmond.json

{
    "archiver": "esmond",
    "data": {
        "url": "http://localhost/esmond/perfsonar/archive/",
        "_auth-token": "bc7----------------------------------------4b"
    }
}

It seems to have the credential information needed for local MA.
I still have nothing in the **/etc/pscheduler/default-archives/** folder as expected/stated in this thread:

 https://lists.internet2.edu/sympa/arc/perfsonar-developer/2016-09/msg00046.html

My current version of pscheduler:
pscheduler-core.noarch              1.0-0.8.rc1.el6           @Internet2-staging
pscheduler-server.noarch            1.0-0.8.rc1.el6           @Internet2-staging
pscheduler-test-idle.noarch         1.0-0.8.rc1.el6           @Internet2-staging
pscheduler-archiver-esmond.noarch   1.0-0.8.rc1.el6           @Internet2-staging
pscheduler-archiver-failer.noarch   1.0-0.8.rc1.el6           @Internet2-staging
pscheduler-archiver-syslog.noarch   1.0-0.8.rc1.el6           @Internet2-staging

Regards,
Ivan

**Comment by arlake228** [comment]
See my email I just sent, what you are seeing is expected and exactly how it is supposed to work.  The meshconfig-agent does NOT SET a default archiver, it reads the measurement_archive blocks from /etc/perfsonar/meshconfig-agent-tasks.conf and submits those in the JSON is gives to the pScheduler API server when creating a task. Closing since there is nothing to fix.
