### ISSUE TITLE
RTT task and hostname as source parameter 

### ISSUE THREAD

**Issue by RockyMM** [perfsonar/pscheduler#183]
RTT task promises that it accepts hostnames as source parameter. The output of `psc task rtt -help`:

    task rtt --source ps2.example.org --dest ps.example.com
    Measure round trip time from ps2.example.org to www.example.com

What is really happening is when using ping as tool for rtt (which is the default) `--source` parameter is translated to `-I` parameter which accepts only interface names or IP addresses.

**Comment by igarny** [comment]
Hi Rade,

As I pointed out and demonstrated on the slack chat, the real problem is that the ping command is initiated using hostname, not exact IP. 
{on CentOS/RH 6}: ping -I param, requires usage of exact IP address.

meaning a resolution from the host name is required for the success of the command.

I would like also to underline: note even the linux implementation in its most basic usage does not allow for ambiguity. Meaning that a user not specifically selecting the correct ping command {ping or ping6} the test will end up with a failure unless by chance the params do allow both stacks.

My call here is to somewhat replicate this behavior and to make the IP version a mandatory parameter.

But if pS Dev want to be more flexible, we could have:
for the cases, where the admin has omitted the IP version. The plugin needs to see how the tests participants resolve
    1) one or more of participants resolves to one and same specific stack, then apply the corresponding IP version
    2) two participants resolve to different stacks: then cancel the test
    3) all participants resolve to both stacks: 
       - either cancel the test because of the ambiguity
       - run the test in IPv6    OR   run both IPv4 and IPv6 tests

Regards,
Ivan

**Comment by igarny** [comment]
[root@pertmp01 ~]# psc task rtt `--source pertmp01` --dest pertmp02
'
Submitting task...
Task URL:
https://pertmp01/pscheduler/tasks/c397a67f-9f75-4e99-ba30-c9d9901f93cd
Fetching first run...

Next run:
https://pertmp01/pscheduler/tasks/c397a67f-9f75-4e99-ba30-c9d9901f93cd/runs/011fc2ef-cd6c-448d-88a3-b50bf0247bec
Starts 2016-10-19T09:12:38Z (~8 seconds)
Ends   2016-10-19T09:12:49Z (~10 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By pertmp01:
    Warning: cannot bind to specified iface, falling back: Operation not permitted
    ping: unknown iface pertmp01


No runs scheduled for this task.



[root@pertmp01 ~]# psc task rtt `--source 10.0.172.16` --dest pertmp02
Submitting task...
Task URL:
https://10.0.172.16/pscheduler/tasks/e3badf46-c34e-4678-8087-b6fa37f13493
Fetching first run...

Next run:
https://10.0.172.16/pscheduler/tasks/e3badf46-c34e-4678-8087-b6fa37f13493/runs/9f345209-f4b1-4ea5-8757-461c30c1f0b3
Starts 2016-10-19T09:13:11Z (~8 seconds)
Ends   2016-10-19T09:13:22Z (~10 seconds)
Waiting for result...

1       10.0.173.64  64 Bytes  TTL 64  RTT   0.3620 ms
2       10.0.173.64  64 Bytes  TTL 64  RTT   0.2790 ms
3       10.0.173.64  64 Bytes  TTL 64  RTT   0.2990 ms
4       10.0.173.64  64 Bytes  TTL 64  RTT   0.3940 ms
5       10.0.173.64  64 Bytes  TTL 64  RTT   0.3110 ms

0% Packet Loss  RTT Min/Mean/Max/StdDev = 0.279000/0.329000/0.394000/0.042000 ms

**Comment by mfeit-internet2** [comment]
Told you it was easy, thanks to some of what I did in #185.

**Comment by igarny** [comment]
Hi Mark,

I have updated pscheduler to:
 pscheduler-server.noarch 0:1.0-0.11.rc1.el6
pscheduler-core.noarch 0:1.0-0.11.rc1.el6
pscheduler-tool-bwctlping.noarch

I believe you have missed that point from above:

> {on CentOS/RH 6}: ping -I param, requires usage of exact IP address.

Above I have also given an example of a successful test and of an unsuccessful. https://github.com/perfsonar/pscheduler/issues/183#issuecomment-254760051

You may argue though, that the problem is for the user to properly set the source, BUT then there is a problem with meshconfig, which defines the source and destination parameters.

Below are the events from syslog

Regards,
Ivan

Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Testing with ping: {"task-uuid": "7d5a020a-016d-4393-aa5d-11288ea4b81d", "participant": 0, "schedule": {"duration": "PT11S", "start": "2016-10-20T11:10:59Z"}, "participant-data": [{}], "test": {"type": "rtt", "spec": {"dest": "pertmp02", "source": "pertmp01", "schema": 1}}, "schema": 1}
Oct 20 11:10:59 pertmp01 ping/run DEBUG    Debug started
Oct 20 11:10:59 pertmp01 ping/run INFO     Started
Oct 20 11:10:59 pertmp01 ping/run INFO     Started
Oct 20 11:10:59 pertmp01 ping/run DEBUG    SPEC: {u'dest': u'pertmp02', u'source': u'pertmp01', u'schema': 1}
Oct 20 11:10:59 pertmp01 ping/run DEBUG    Running ping -n -c 5 -i 1.0 -I pertmp01 -W 1.0 10.0.173.64
Oct 20 11:10:59 pertmp01 ping/run DEBUG    Timeout is 0:00:07
Oct 20 11:10:59 pertmp01 ping/run DEBUG    Program exited 2: Warning: cannot bind to specified iface, falling back: Operation not permitted#012ping: unknown iface pertmp01
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Test Succeeded: {"diags": "ping -n -c 5 -i 1.0 -I pertmp01 -W 1.0 10.0.173.64", "result": null, "succeeded": false, "error": "Warning: cannot bind to specified iface, falling back: Operation not permitted\nping: unknown iface pertmp01\n"}
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Stored local result
Oct 20 11:10:59 pertmp01 runner DEBUG    Schedule change.
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Doing lead participant duties
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Only one participant; not waiting.
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Runs are ['https://pertmp01/pscheduler/tasks/7d5a020a-016d-4393-aa5d-11288ea4b81d/runs/90d57207-e970-4ce4-84c2-b4e25922ce07']
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Local run returned 0
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Accumulated local result
Oct 20 11:10:59 pertmp01 runner DEBUG    132552: Full result: [{"diags": "ping -n -c 5 -i 1.0 -I pertmp01 -W 1.0 10.0.173.64", "result": null, "succeeded": false, "error": "Warning: cannot bind to specified iface, falling back: Operation not permitted\nping: unknown iface pertmp01\n"}]
