### ISSUE TITLE
bug: pscheduler keeps trying a local esmond

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#191]
Hi Mark,

For whatever reason pscheduler keeps trying a local esmond. I do not have a local Esmond. See logs and config below.

Could it be stalled tasks from say a week ago?

Regards,
Ivan

[root@pertmp01 ~]# grep esmond /etc/perfsonar/meshconfig-agent-tasks.conf
    database   http://`pertcs01.switch.ch`/esmond/perfsonar/archive/
    type   esmond/latency
    database   http://`pertcs01.switch.ch`/esmond/perfsonar/archive/
    type   esmond/throughput
    database   http://`pertcs01.switch.ch`/esmond/perfsonar/archive/
    type   esmond/traceroute
[root@pertmp01 ~]# ls -a /etc/pscheduler/default-archives/
.  ..
[root@pertmp01 ~]#

Oct 19 13:54:25 pertmp01 archiver-esmond/archive DEBUG    Posting metadata to http://localhost/esmond/perfsonar/archive/: {'time-duration': 26.0, 'pscheduler-test-type': 'throughput', 'source': '10
.0.172.16', 'measurement-agent': '10.0.178.53', 'input-destination': u'10.0.178.53', 'destination': '10.0.178.53', 'event-types': [{'event-type': 'failures'}, {'event-type': 'throughput'}, {'event-
type': 'throughput-subintervals'}, {'event-type': 'packet-retransmits'}, {'event-type': 'packet-retransmits-subintervals'}], 'subject-type': 'point-to-point', 'ip-transport-protocol': 'tcp', 'input
-source': u'pertmp01.switch.ch', 'bw-parallel-streams': 1, 'tool-name': u'pscheduler/iperf3'}
Oct 19 13:54:25 pertmp01 archiver-esmond/archive DEBUG    Posting metadata to http://localhost/esmond/perfsonar/archive/: {'time-duration': 26.0, 'pscheduler-test-type': 'throughput', 'source': '10
.0.172.16', 'measurement-agent': '10.0.178.53', 'input-destination': u'10.0.178.53', 'destination': '10.0.178.53', 'event-types': [{'event-type': 'failures'}, {'event-type': 'throughput'}, {'event-
type': 'throughput-subintervals'}, {'event-type': 'packet-retransmits'}, {'event-type': 'packet-retransmits-subintervals'}], 'subject-type': 'point-to-point', 'ip-transport-protocol': 'tcp', 'input
-source': u'pertmp01.switch.ch', 'bw-parallel-streams': 1, 'tool-name': u'pscheduler/iperf3'}
Oct 19 13:54:25 pertmp01 archiver DEBUG    Archiver exited 0
Oct 19 13:54:25 pertmp01 archiver DEBUG    Returned JSON from archiver: {"retry": "PT60M", "succeeded": false, "error": "404: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<ti
tle>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /esmond/perfsonar/archive/ was not found on this server.</p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at loca
lhost Port 80</address>\n</body></html>\n"}
Oct 19 13:54:25 pertmp01 archiver DEBUG    Returned errors from archiver:
Oct 19 13:54:25 pertmp01 archiver DEBUG    Failed: 4f7bbfdb-c6cd-4193-abc9-4e46200dec70 to esmond: {"retry": "PT60M", "succeeded": false, "error": "404: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.
0//EN\">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /esmond/perfsonar/archive/ was not found on this server.</p>\n<hr>\n<address>Apache/2.2
.15 (CentOS) Server at localhost Port 80</address>\n</body></html>\n"}
Oct 19 13:54:25 pertmp01 archiver DEBUG    Rescheduling for 2016-10-19 14:54:25.247812+00:00

**Comment by arlake228** [comment]
Did you previously have meshconfig-agent-tasks.conf pointed at localhost
and then changed it to the new address?



On October 19, 2016 at 10:15:10 AM, Ivan Garnizov (notifications@github.com)
wrote:

Hi Mark,

For whatever reason pscheduler keeps trying a local esmond. I do not have a
local Esmond. See logs and config below.

Could it be stalled tasks from say a week ago?

Regards,
Ivan

[root@pertmp01 ~]# grep esmond /etc/perfsonar/meshconfig-agent-tasks.conf
database http://pertcs01.switch.ch/esmond/perfsonar/archive/
type esmond/latency
database http://pertcs01.switch.ch/esmond/perfsonar/archive/
type esmond/throughput
database http://pertcs01.switch.ch/esmond/perfsonar/archive/
type esmond/traceroute
[root@pertmp01 ~]# ls -a /etc/pscheduler/default-archives/
. ..
[root@pertmp01 ~]#

Oct 19 13:54:25 pertmp01 archiver-esmond/archive DEBUG Posting metadata to
http://localhost/esmond/perfsonar/archive/: {'time-duration': 26.0,
'pscheduler-test-type': 'throughput', 'source': '10
.0.172.16', 'measurement-agent': '10.0.178.53', 'input-destination':
u'10.0.178.53', 'destination': '10.0.178.53', 'event-types':
[{'event-type': 'failures'}, {'event-type': 'throughput'}, {'event-
type': 'throughput-subintervals'}, {'event-type': 'packet-retransmits'},
{'event-type': 'packet-retransmits-subintervals'}], 'subject-type':
'point-to-point', 'ip-transport-protocol': 'tcp', 'input
-source': u'pertmp01.switch.ch', 'bw-parallel-streams': 1, 'tool-name':
u'pscheduler/iperf3'}
Oct 19 13:54:25 pertmp01 archiver-esmond/archive DEBUG Posting metadata to
http://localhost/esmond/perfsonar/archive/: {'time-duration': 26.0,
'pscheduler-test-type': 'throughput', 'source': '10
.0.172.16', 'measurement-agent': '10.0.178.53', 'input-destination':
u'10.0.178.53', 'destination': '10.0.178.53', 'event-types':
[{'event-type': 'failures'}, {'event-type': 'throughput'}, {'event-
type': 'throughput-subintervals'}, {'event-type': 'packet-retransmits'},
{'event-type': 'packet-retransmits-subintervals'}], 'subject-type':
'point-to-point', 'ip-transport-protocol': 'tcp', 'input
-source': u'pertmp01.switch.ch', 'bw-parallel-streams': 1, 'tool-name':
u'pscheduler/iperf3'}
Oct 19 13:54:25 pertmp01 archiver DEBUG Archiver exited 0
Oct 19 13:54:25 pertmp01 archiver DEBUG Returned JSON from archiver:
{"retry": "PT60M", "succeeded": false, "error": "404: <!DOCTYPE HTML PUBLIC
\"-//IETF//DTD HTML 2.0//EN\">\n\n tle>404 Not Found\n\n
Not Found \n

The requested URL /esmond/perfsonar/archive/ was not found on this server.
\n
------------------------------
\nApache/2.2.15 (CentOS) Server at loca
lhost Port 80\n\n"}
Oct 19 13:54:25 pertmp01 archiver DEBUG Returned errors from archiver:
Oct 19 13:54:25 pertmp01 archiver DEBUG Failed:
4f7bbfdb-c6cd-4193-abc9-4e46200dec70 to esmond: {"retry": "PT60M",
"succeeded": false, "error": "404: <!DOCTYPE HTML PUBLIC \"-//IETF//DTD
HTML 2.
0//EN\">\n\n404 Not Found\n\n Not Found \n

The requested URL /esmond/perfsonar/archive/ was not found on this server.
\n
------------------------------
\nApache/2.2
.15 (CentOS) Server at localhost Port 80\n\n"}
Oct 19 13:54:25 pertmp01 archiver DEBUG Rescheduling for 2016-10-19
14:54:25.247812+00:00

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/pscheduler/issues/191>, or mute the thread

**Comment by igarny** [comment]
Hi Andy,

Yes, but that was last week. 
That is why I asked for how to clear the pscheduler's schedule.

**Comment by mfeit-internet2** [comment]
This is not a bug in pScheduler; if it's being told to archive to local esmond, that's what it's going to try.

Sounds like meshconfig might not be removing old tasks when the mesh changes.
