### ISSUE TITLE
bug: psc backward compatibility fails: "Test failed 1: iperf3 requires exactly 2 participants, got 1"

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#194]
>[root@pertmp01 ~]# pscheduler task --tool iperf3 throughput --source pertmp01 --dest pertmp04

Submitting task...
Task URL:
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332
Fetching first run...

Next run:
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90
Starts 2016-10-20T12:42:22Z (~8 seconds)
Ends   2016-10-20T12:42:38Z (~15 seconds)
less /vaWaiting for result...
r/log/messages
Run failed.  The following errors were reported:
By pertmp01:
      (No error reported)

> [root@pertmp01 ~]# bwctl -c pertmp04

bwctl: Using tool: iperf3
bwctl: 16 seconds until test results available

SENDER START
Connecting to host 10.0.173.66, port 5658
[ 15] local 10.0.172.16 port 54528 connected to 10.0.173.66 port 5658
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[ 15]   0.00-1.00   sec   241 MBytes  2025 Mbits/sec   61   1.62 MBytes
[ 15]   1.00-2.00   sec   250 MBytes  2097 Mbits/sec    0   1.81 MBytes
[ 15]   2.00-3.00   sec   270 MBytes  2265 Mbits/sec    0   2.00 MBytes
[ 15]   3.00-4.00   sec   266 MBytes  2233 Mbits/sec    0   2.30 MBytes
[ 15]   4.00-5.00   sec   265 MBytes  2223 Mbits/sec    0   2.70 MBytes
[ 15]   5.00-6.00   sec   270 MBytes  2265 Mbits/sec   15   1.59 MBytes
[ 15]   6.00-7.00   sec   269 MBytes  2254 Mbits/sec    0   1.80 MBytes
[ 15]   7.00-8.00   sec   272 MBytes  2286 Mbits/sec    0   2.00 MBytes
[ 15]   8.00-9.00   sec   269 MBytes  2254 Mbits/sec    0   2.34 MBytes
[ 15]   9.00-10.00  sec   269 MBytes  2255 Mbits/sec    0   2.78 MBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[ 15]   0.00-10.00  sec  2.58 GBytes  2216 Mbits/sec   76             sender
[ 15]   0.00-10.00  sec  2.58 GBytes  2213 Mbits/sec                  receiver

iperf Done.

SENDER END

Oct 20 12:42:13 pertmp01 scheduler DEBUG    Scheduled for 2016-10-20 12:42:22+00:00 - 2016-10-20 12:42:38+00:00 at https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90
Oct 20 12:42:13 pertmp01 scheduler DEBUG    Received notifications.
Oct 20 12:42:16 pertmp01 ticker DEBUG    Tick
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=303, Connection to ([pertmp01.switch.ch]:861) from ([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=303, Connection to ([pertmp01.switch.ch]:861) from ([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=466, ControlSession([pertmp01.switch.ch]:861) accepted from userid(nil):([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=466, ControlSession([pertmp01.switch.ch]:861) accepted from userid(nil):([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 ticker DEBUG    Next check in 14 seconds
Oct 20 12:42:22 pertmp01 participant-data INFO     Started
Oct 20 12:42:22 pertmp01 participant-data INFO     Started
Oct 20 12:42:22 pertmp01 runner DEBUG    Schedule change.
Oct 20 12:42:22 pertmp01 runner DEBUG    134508: Testing with iperf3: {"task-uuid": "cff31772-a994-4047-aca0-26577ccbb332", "participant": 0, "schedule": {"duration": "PT16S", "start": "2016-10-20T12:42:22Z"}, "participant-data": [{"iperf3_cmd": "/usr/bin/iperf3"}], "test": {"type": "throughput", "spec": {"dest": "pertmp04", "source": "pertmp01", "schema": 1}}, "schema": 1}
Oct 20 12:42:22 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 20 12:42:22 pertmp01 runner DEBUG    Nothing to do.
Oct 20 12:42:22 pertmp01 runner DEBUG    Next run or check in 0:01:00
Oct 20 12:42:23 pertmp01 run DEBUG    Debug started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 run DEBUG    Debug started
Oct 20 12:42:23 pertmp01 run DEBUG    Debug started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 run INFO     Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG    Debug started
Oct 20 12:42:23 pertmp01 tool-iperf3/run INFO     Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run INFO     Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG    starting iperf3 tool
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG    

> Input is {u'task-uuid': u'cff31772-a994-4047-aca0-26577ccbb332', u'participant': 0, u'schedule' {u'duration': u'PT16S', u'start': u'2016-10-20T12:42:22Z'}, u'participant-data': [{u'iperf3_cmd': u'/usr/bin/iperf3'}], u'test': {u'type': u'throughput', u'spec': {u'dest': u'pertmp04', u'source': u'pertmp01', u'schema': 1}}, u'schema': 1}

Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Test failed 1: iperf3 requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 participant-data INFO     Started
Oct 20 12:42:23 pertmp01 participant-data INFO     Started
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Stored local result
Oct 20 12:42:23 pertmp01 runner DEBUG    Schedule change.
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Doing lead participant duties
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Only one participant; not waiting.
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Runs are ['https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90']
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Local run returned 1
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Tool returned failure: iperf3 requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Accumulated local result
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Full result: [null]
Oct 20 12:42:23 pertmp01 runner DEBUG    134508: Storing full result in https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90, params={"result-full": [null]}
Oct 20 12:42:23 pertmp01 runner DEBUG    Got 0 upcoming rows
Oct 20 12:42:23 pertmp01 runner DEBUG    Nothing to do.
Oct 20 12:42:23 pertmp01 runner DEBUG    Next run or check in 0:01:00

**Comment by daldoyle** [comment]
This is operator error. You can’t specify —tool iperf3 because it will try to do everything via pScheduler’s implementation of iperf3, which correctly failed assuming that pertmp04 is not running pScheduler. If you leave the —tool argument out, I would expect this to work. Can you verify?

Dan Doyle
GlobalNOC Software Developer
1-812-856-3892
daldoyle@globalnoc.iu.edu

**Comment by arlake228** [comment]
This is not a bug. If you specify the “iperf3” tool then it will try to use
iperf3 directly. BWCTL is the bwctliperf3 tool (e.g. psc task —tool
bwctliperf3 throughput .. …). You wither need to not specify the tool or
specify bwctliperf3 as one of the tools you want.





On October 20, 2016 at 8:58:31 AM, Ivan Garnizov (notifications@github.com)
wrote:

[root@pertmp01 ~]# pscheduler task --tool iperf3 throughput --source
pertmp01 --dest pertmp04

Submitting task...
Task URL:
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332
Fetching first run...

Next run:
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90
Starts 2016-10-20T12:42:22Z (~8 seconds)
Ends 2016-10-20T12:42:38Z (~15 seconds)
less /vaWaiting for result...
r/log/messages
Run failed. The following errors were reported:
By pertmp01:
(No error reported)

[root@pertmp01 ~]# bwctl -c pertmp04

bwctl: Using tool: iperf3
bwctl: 16 seconds until test results available

SENDER START
Connecting to host 10.0.173.66, port 5658
[ 15] local 10.0.172.16 port 54528 connected to 10.0.173.66 port 5658
[ ID] Interval Transfer Bandwidth Retr Cwnd
[ 15] 0.00-1.00 sec 241 MBytes 2025 Mbits/sec 61 1.62 MBytes
[ 15] 1.00-2.00 sec 250 MBytes 2097 Mbits/sec 0 1.81 MBytes
[ 15] 2.00-3.00 sec 270 MBytes 2265 Mbits/sec 0 2.00 MBytes
[ 15] 3.00-4.00 sec 266 MBytes 2233 Mbits/sec 0 2.30 MBytes
[ 15] 4.00-5.00 sec 265 MBytes 2223 Mbits/sec 0 2.70 MBytes
[ 15] 5.00-6.00 sec 270 MBytes 2265 Mbits/sec 15 1.59 MBytes
[ 15] 6.00-7.00 sec 269 MBytes 2254 Mbits/sec 0 1.80 MBytes
[ 15] 7.00-8.00 sec 272 MBytes 2286 Mbits/sec 0 2.00 MBytes
[ 15] 8.00-9.00 sec 269 MBytes 2254 Mbits/sec 0 2.34 MBytes
[ 15] 9.00-10.00 sec 269 MBytes 2255 Mbits/sec 0 2.78 MBytes
------------------------------

[ ID] Interval Transfer Bandwidth Retr
[ 15] 0.00-10.00 sec 2.58 GBytes 2216 Mbits/sec 76 sender
[ 15] 0.00-10.00 sec 2.58 GBytes 2213 Mbits/sec receiver

iperf Done.

SENDER END

Oct 20 12:42:13 pertmp01 scheduler DEBUG Scheduled for 2016-10-20
12:42:22+00:00 - 2016-10-20 12:42:38+00:00 at
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90
Oct 20 12:42:13 pertmp01 scheduler DEBUG Received notifications.
Oct 20 12:42:16 pertmp01 ticker DEBUG Tick
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=303, Connection
to ([pertmp01.switch.ch]:861) from ([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=303, Connection
to ([pertmp01.switch.ch]:861) from ([pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=466,
ControlSession([pertmp01.switch.ch]:861) accepted from userid(nil):([
pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 owampd[31671]: FILE=sapi.c, LINE=466,
ControlSession([pertmp01.switch.ch]:861) accepted from userid(nil):([
pertmp06.switch.ch]:45897)
Oct 20 12:42:16 pertmp01 ticker DEBUG Next check in 14 seconds
Oct 20 12:42:22 pertmp01 participant-data INFO Started
Oct 20 12:42:22 pertmp01 participant-data INFO Started
Oct 20 12:42:22 pertmp01 runner DEBUG Schedule change.
Oct 20 12:42:22 pertmp01 runner DEBUG 134508: Testing with iperf3:
{"task-uuid": "cff31772-a994-4047-aca0-26577ccbb332", "participant": 0,
"schedule": {"duration": "PT16S", "start": "2016-10-20T12:42:22Z"},
"participant-data": [{"iperf3_cmd": "/usr/bin/iperf3"}], "test": {"type":
"throughput", "spec": {"dest": "pertmp04", "source": "pertmp01", "schema":
1}}, "schema": 1}
Oct 20 12:42:22 pertmp01 runner DEBUG Got 0 upcoming rows
Oct 20 12:42:22 pertmp01 runner DEBUG Nothing to do.
Oct 20 12:42:22 pertmp01 runner DEBUG Next run or check in 0:01:00
Oct 20 12:42:23 pertmp01 run DEBUG Debug started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 run DEBUG Debug started
Oct 20 12:42:23 pertmp01 run DEBUG Debug started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 run INFO Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG Debug started
Oct 20 12:42:23 pertmp01 tool-iperf3/run INFO Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run INFO Started
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG starting iperf3 tool
Oct 20 12:42:23 pertmp01 tool-iperf3/run DEBUG

Input is {u'task-uuid': u'cff31772-a994-4047-aca0-26577ccbb332',
u'participant': 0, u'schedule' {u'duration': u'PT16S', u'start':
u'2016-10-20T12:42:22Z'}, u'participant-data': [{u'iperf3_cmd':
u'/usr/bin/iperf3'}], u'test': {u'type': u'throughput', u'spec': {u'dest':
u'pertmp04', u'source': u'pertmp01', u'schema': 1}}, u'schema': 1}

Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Test failed 1: iperf3
requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 participant-data INFO Started
Oct 20 12:42:23 pertmp01 participant-data INFO Started
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Stored local result
Oct 20 12:42:23 pertmp01 runner DEBUG Schedule change.
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Doing lead participant duties
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Only one participant; not
waiting.
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Runs are ['
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90
']
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Local run returned 1
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Tool returned failure: iperf3
requires exactly 2 participants, got 1
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Accumulated local result
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Full result: [null]
Oct 20 12:42:23 pertmp01 runner DEBUG 134508: Storing full result in
https://pertmp01/pscheduler/tasks/cff31772-a994-4047-aca0-26577ccbb332/runs/3fe3da65-2ef9-47bd-ab3d-6e9a10fcba90,
params={"result-full": [null]}
Oct 20 12:42:23 pertmp01 runner DEBUG Got 0 upcoming rows
Oct 20 12:42:23 pertmp01 runner DEBUG Nothing to do.
Oct 20 12:42:23 pertmp01 runner DEBUG Next run or check in 0:01:00

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/pscheduler/issues/194>, or mute the thread

**Comment by mfeit-internet2** [comment]
Behaving as designed.

Andy's backward-compatibility stuff is set up to figure out the situation automagically so you don't have to.

**Comment by igarny** [comment]
it worked on my side with each of the suggested solutions
Thanks
