### ISSUE TITLE
nuttcp fails

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#217]
I'm getting this error. I've try to 4.0 hosts (CentOS 6 and CentOS7, and to 3.5 hosts.

Maybe its not using the right port? 
Maybe it should say what port its trying to use?

pscheduler task --tool nuttcp throughput --dest antg-staging
Submitting task...
Task URL:
https://test-pt1.es.net/pscheduler/tasks/7b180bf5-df0d-4b7a-b060-7899ed08c435
Fetching first run...

Next run:
https://test-pt1.es.net/pscheduler/tasks/7b180bf5-df0d-4b7a-b060-7899ed08c435/runs/ae68ab15-fcb7-4c26-ad07-060e06870015
Starts 2016-11-05T09:16:33-07:00 (~47 seconds)
Ends   2016-11-05T09:16:49-07:00 (~15 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By test-pt1.es.net:
    nuttcp returned an error: 
    nuttcp-t: Info: attempting to switch to deprecated "classic" mode
    nuttcp-t: Info: will use less reliable transmitter side statistics
    nuttcp-t: v8.1.3: Error: connect: Connection refused
    errno=111
    

By antg-staging:
      (No error reported)

**Comment by daldoyle** [comment]
I believe this was because of nuttcp using the stock port of 5000 which was outside of the original recommended bwctl port range and thus not opened on some firewalls along the way. The default port for nuttcp has been changed to 5001 in the code to be inside of that range.

Before the next release, you can also change this in /etc/pscheduler/tool/nuttcp.conf - uncomment and change the value for the "server_port" variable. You should not need to restart anything for this to take effect. Can you confirm this works?

**Comment by daldoyle** [comment]
Poked around at this more after Brian showed me an example, turned out to be a parsing issue. Committed and fixed.
