### ISSUE TITLE
add support for iperf3 --fq-rate option

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#256]
iperf3 has the following new option that we need to be able to configure via for a test mesh:
--fq-rate N

Note that this is separate from --bandwidth, and works for both TCP and UDP.

See issue # 48 in mesh config for corresponding mesh configure issue.

**Comment by mfeit-internet2** [comment]
Please give some thought to this before doing it:

The `throughput` test is an abstraction for specifying throughput measurements and how they should be done and the tool plugins figure out the best way to do it.  I would prefer it if the test spec didn't become a proxy for iperf3's command line switches.

The pacing rate is set with `SO_MAX_PACING RATE`, which is independent of the queue discipline.  Right now, FQ is the only one that honors it, but that could change in the future and they're going to have to revisit the choice of command-line switch.  I'd have to check if setting that option when the interface isn't set for FQ results in an error, in which case iperf3 will fall back to software.  If it doesn't, a misconfigured system will turn into a firehose if `--fq-rate` is used and `-b` isn't.

Ergo, I would suggest that...

 * The `bandwidth` test parameter be used to specify the maximum bandwidth for the test (as it always has).
 * The tool plugin decides how to best carry out the test given the parameters using what the tool has available.
 * We add parameters to influence how that decision is made:
    * `queue-discipline` - Forces a queue discipline onto the interface for the duration of the test.  Values would be one from the [list of queuing disciplines](http://man7.org/linux/man-pages/man8/tc.8.html#CLASSLESS_QDISCS).
    * `pacing` - Has values `soft` to force software-based pacing and `system` to use the system's features to do it.
* We consider making use of the traffic control features in the kernel outside of iperf3 and anything else.  (See http://tldp.org/HOWTO/Adv-Routing-HOWTO/lartc.ratelimit.single.html for details.)  That would also allow us to add bandwidth controls to the plugins for tools that don't support pacing.  Iperf3's built-in pacing could be used for UDP tests to keep from burning a lot of CPU and flooding the network stack.

We'd also need to wait for 3.1.5 to trickle into EPEL or distribute it ourselves.

**Comment by mfeit-internet2** [comment]
Kicking this into 1.0 since it's not likely to be resolved in the next week.

**Comment by bmah888** [comment]
Few comments...not necessarily with any particular point to be made:

If the interface isn't configured for FQ, specifying `--fq-rate` has no effect.  That's unfortunate but the relevant `setsockopt(SO_MAX_PACING_RATE)` call doesn't even return an error in that case.  I think that's probably because there's no way of knowing the outbound interface at the time the socket option is set (in the most general case anyway).

`--fq-rate` and `--bandwidth` control two separate pacing mechanisms that basically operate in series.  If `--fq-rate` doesn't work (as in the situation above), in a sense yes `--bandwidth` is the fallback.  Note that for TCP tests, the default is for iperf3 is to send as fast as it can, while for UDP, the default is 1 Mbps.  I'm not sure whether or not those defaults would ever come in to play with pScheduler (i.e. does pScheduler+plugin always explicitly set a bandwidth?).  But the "firehose" scenario is, I think, unlikely, or at least I wouldn't characterize iperf3's behavior as such under the circumstances.

You have a point about the naming of the option.  We'll cross or burn that bridge when we come to it.

I'm a little leery of mucking around with the queueing discipline on an interface for a test.  At the least I don't think iperf3 should be doing it.  It might make sense, as you say, to do it in a tool-independent way so other plugins can take advantage of it.

**Comment by bltierney** [comment]
I think this option is VERY important. Bumping it back to 1.0.1. Lets discuss more after the release.

**Comment by bltierney** [comment]
One more thing in case its not clear: All I'm asking for is the ability to set  iperf3's --fq-rate flag from the mesh config. Nothing more than that. I cant think of a way that this could be used to increase test throughput. It will only be possible to throttle it, which is what I've gotten many requests for.

**Comment by daldoyle** [comment]
Playing around with this a bit this morning directly with iperf3.2, it looks like you can safely set both bandwidth and fq-rate and it seems to do the right thing. 

TCP
fq-rate 100M => ~87M
bandwidth 100M => 100M
fq-rate 100M + bandwidth 100M => 100M

UDP
fq-rate 100M => 1M (looks like default UDP rate)
bandwidth 100M => 100M
fq-rate 100M + bandwidth 100M => ~73M

Setting both may be the best immediate implementation since it seems that iperf3 will fallback to doing it itself if the setsockopt fails, will have to poke Bruce about that to confirm.

If so we'll want to abstract the names out a bit to help in the future as Mark suggested. Being able to do arbitrary qdisc settings is interesting, though not particularly wild about the idea since that could impact other things on the system in a hard to debug fashion (background tests, other things on the server, etc).

**Comment by daldoyle** [comment]
Going to include this when EL6 support is dropped. Moving to 4.0.2

**Comment by bltierney** [comment]
I think its time to revisit this topic, and move it up the queue.

Note that this option is now in iperf2 as well.

**Comment by marcosfsch** [comment]
At RNP we are trying to use 10G testpoints on both 1G and 10G throughput meshes. But we are getting.
When testing from a 10G interface to 1G we are getting 300Mbps. 
Troubleshooting with iperf3 directly we colud get around 900Mbps using fq-rate 900M + bandwidth 900M. So we are interested in working in this issue.
Are there any new ideas or proposals?

PS: BBR also solves the problem, but at the cost of a lot of retransmissions. On the short term BBR is an option, but we were able to achieve the same performance with zero retransmits using fq-rate and are interested in it to have a more accurate measurement of the network characteristics.

**Comment by mfeit-internet2** [comment]
After some discussion with @bltierney:

- [ ] Add `queue-discipline` parameter.
- [ ] For iperf3, if QD is `fq`, set the `--fq-rate` parameter to match `bandwidth`.
- [ ] For iperf3, If `bandwidth` is not set, `fq-rate` is not set.

**Comment by bltierney** [comment]
note that --fq-rate also works for QD = fq_codel, and that iperf2 also has a --fq-rate flag.
