### ISSUE TITLE
pSched to update remote participants from the schedule list on system shutdown (restart?)

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#277]
I am looking at having a mitigation of the multiple retries issue on test failures with a dead host.
Also related to #148

It would be nice on a system shutdown, pscheduler to send an update to all remote participants. Obviously the expectations here cannot be high, because of the TCP handshake mechanism.

**Comment by mfeit-internet2** [comment]
This may not necessarily be desirable behavior.  A quick reboot would mean having to reschedule all tests afterward.

If a task on a non-lead participant is orphaned because the lead goes away, the worst case is that runs will continue to exist out to the schedule horizon (currently `P1D`) from the last time the lead tried to schedule anything.

**Comment by igarny** [comment]
I see you have a different point of view. In fact I did not envision removal or deprecation of scheduled test with the participant going offline.
I came to this proposal from the issue with multiple retries on a failing test. The idea is to automatically reconfigure the scheduled tests to 1~2 max retries on a failure.

**Comment by mfeit-internet2** [comment]
The first comment didn't read that way.  Please edit it to clarify.
