### ISSUE TITLE
psc limits failure to validate in runs blocks measurements

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#278]
Jan 27 14:42:24 psps-test2-mgmt pscheduler-api ERROR    Exception: RuntimeError: Failed to validate limit: Process took too long
 to run.#012Traceback (most recent call last):#012  File "./pschedulerapiserver/runs.py", line 435, in tasks_uuid_runs_run#012
File "./pschedulerapiserver/runs.py", line 77, in __evaluate_limits#012  File "/usr/lib/python2.6/site-packages/pscheduler/limit
processor/limitprocessor.py", line 126, in process#012    = self.applications.check(task, classifications, check_schedule)#012
File "/usr/lib/python2.6/site-packages/pscheduler/limitprocessor/applicationset.py", line 223, in check#012    check_schedule)#0
12  File "/usr/lib/python2.6/site-packages/pscheduler/limitprocessor/applicationset.py", line 159, in __check_application#012
 = self.__check_group(task, group, check_schedule)#012  File "/usr/lib/python2.6/site-packages/pscheduler/limitprocessor/applica
tionset.py", line 117, in __check_group#012    evaluated = self.limits.check(task, limit, check_schedule)#012  File "/usr/lib/py
thon2.6/site-packages/pscheduler/limitprocessor/limitset.py", line 160, in check#012    evaluated = evaluator.evaluate(task)#012
  File "/usr/lib/python2.6/site-packages/pscheduler/limitprocessor/limit/test.py", line 83, in evaluate#012    raise RuntimeErro
r("Failed to validate limit: %s" % stderr)#012RuntimeError: Failed to validate limit: Process took too long to run.

At the same time on CLI I get:
[root@psps-test2-mgmt ~]# pscheduler validate-limits
Limit configuration is valid.

as a matter of fact I did have myself problems with the validation beforehand, so I had to stop pscheduler services to get initially the limits checked. But on the subsequent runs I did not have the problem

**Comment by igarny** [comment]
I have some minor updates here. In fact it really depends on the work load of pscheduler (my guess).
There are times when CLI tests also end up with "Process took too long" errors.

My guess is not based on any indication, though.

**Comment by mfeit-internet2** [comment]
This was caused by a call-out to one of the methods in a test plugin taking longer than the timeout set inside the limit processor.

The two methods involved are `limit-is-valid` and `limit-passes`, neither of which does much of anything beyond validating JSON and checking to see if a task proposal meets a given limit.  The timeout for this is five seconds, which seems like more than sufficient time.

This ticket was written when we were in the middle of performance tuning pScheduler and, if I'm not mistaken, when the machine that generated this error was still a single-core system.  I don't think there's a software problem to be solved here.
