### ISSUE TITLE
Automatically run pylint against code

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#334]
pylint is super useful at finding syntax errors. We should integrate it somewhere in our build process so we get quicker notice when things like that creep in. Some of the coding standard enforcement features you can use it for may be nice too.

**Comment by mfeit-internet2** [comment]
I've started using pylint and flycheck in Emacs when I do my development.  There are a few of its nitpicks I could live without, but in general this is worth considering.

Between 1.0 and 1.1, I'm probably going to pick one package per week and spend an hour doing lint-related cleanups.

**Comment by montegoode** [comment]
I find the best way of doing this is to integrate pylint into your editor rather than running the linter as a separate step. There is a couple of ways of doing this in Sublime Text that I know of.

A specific and general point about @mfeit-internet2 not liking some of pylint's more pedantic moments. The way we've done this on other projects is to check in a `pylint.rc` file into the source - that way everyone can use the same linting rules. And if you are going to end up with a bunch of repetitive errors that are part and parcel of your code base (like it complaining about "magic class attributes" in django projects) then you can just globally disable them in the the shared .rc file.

I will probably do this in my branch when I get to that point. I'm currently just focusing on getting the unit tests happening and fixing pep8 errors (which my editor can take care of).

**Comment by daldoyle** [comment]
Plan is to integrate this into jenkins build process, I'm going to take a look at it this week hopefully

**Comment by mfeit-internet2** [comment]
Question for discussion:  Do we want to set up the Makefiles for anything containing Python to do a check as part of its build and die there if there's a fatal problem or try to do one global check of everything.

The former would make a lot of sense of pScheduler since it would catch these things as each package is built during development.

**Comment by daldoyle** [comment]
This is done for now, initial version works and is reporting in jenkins.
