### ISSUE TITLE
pscheduler becomes unresponsive as schedule gets full

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#342]
Commands such as the following all timeout on sacr-pt1.es.net, which has a very full schedule.

pscheduler schedule --filter-test=throughput +PT30M

pscheduler plot-schedule -PT30M +PT30M > plot.png

This command works:
pscheduler monitor --refresh=5  
and shows many "Non-Starters"

**Comment by mfeit-internet2** [comment]
This is probably related to #346.

**Comment by bltierney** [comment]
I still see this problem, so re-opening.

**Comment by mfeit-internet2** [comment]
Notes on what we found:

Pulling schedule for a minute's worth of schedule from this machine takes over 30 seconds.

The schedule query takes a long time to return from the web server when queried with `curl`, which rules out the client program (`schedule`).

Andy reports the DB query takes ~30 ms to run.

Nothing in the Flask code is particularly heavy, and pulled out into a test program runs in no time.

The only conclusion I can reach is that the thread processing the request is being starved out by contention for the GIL.  The defaults are used in the current configuration.  Andy's going to see how the 10 processes and 5 threads used by Esmond worked out.

**Comment by arlake228** [comment]
Just committed what I think is the fix. Changing the wsgi settings had no effect on performance. It also occurs to me that all other API calls that hit the API return quickly, so its specific to schedule. I ran the server-side schedule command through a profiler, almost the entire time is spent in 412 calls to gethostbyaddr which in turn was called by pscheduler.api_url. Easy fix to move it out of the loop, which I did in the commit.

We should maybe quickly discuss tomorrow changing the wsgi process and thread settings even though it wasn't the issue here. My gut says its a good thing, but limited testing doesn't show much of a difference.

**Comment by mfeit-internet2** [comment]
The function behind the call that drives the monitor could probably use some tuning up.  The individual queries that make it up seem pretty quick.

**Comment by bltierney** [comment]
Note that the following command still times out:

 pscheduler plot-schedule --host sacr-pt1.es.net -PT6H

Agree this can wait till after rc3

**Comment by arlake228** [comment]
One thought too is that we provide an option (or maybe even by default) leave out backgroundmulti tasks since they don't tell us a whole lot anyways given that they don't affect the schedule and generate huge numbers of runs to display.

**Comment by mfeit-internet2** [comment]
That's something that we can do when the API includes the ability to filter, which it doesn't right now.
