### ISSUE TITLE
Pass lead-bind legitimately into participants method

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#364]
Add whatever is in `lead-bind` to the JSON passed into the `participants` method instead of using the environment hack.

This will require that any `participants` method calling `api_has_*()` will have to pass in the binding manually if it exists.  (Not a huge deal.)

Old JSON:
```
{ ... Test Spec ... }
```
New JSON:
```
{
    "lead-bind": "xxx.foo.org",
    "spec": { ... Test Spec ... }
}
```

~I think this is equally hacky.  See #365 for an alternate proposal.~

**Comment by arlake228** [comment]
Another idea that we've discussed before but not in this context: make lead-bind a config option on the server side and have the participants function pull it from the local config, so no json changes needed. Honestly this seems a little more sensible to me independent of this issue since having a remote client having enough knowledge of the management interfaces, etc seems a bit of a stretch. We could either keep the lead-bind option and document that it won't work in this case or maybe drop it entirely?

Also, you'd probably want such an option to to ether take a simple string that is the default (e.g. lead_bind_address X.X.X.X) or a map that allows you to change it based on the address you are trying reach. e.g.

lead_bind_address:
    remote_address: Y.Y.Y.Y
    local_address: X.X.X.1

lead_bind_address:
    remote_address: Z.Z.Z.Z
    local_address: X.X.X.2

Not sure that i like this better but throwing the idea out there.

**Comment by mfeit-internet2** [comment]
Can't say I'm sure there's a god way around this, although with a little creative thinking, I might be able to resurrect #365 in a way that makes sense.

**Comment by mfeit-internet2** [comment]
Decided:  https://github.com/perfsonar/pscheduler/issues/370#issuecomment-287367558

Did all that; commit to follow.

**Comment by mfeit-internet2** [comment]
That should do it.
