### ISSUE TITLE
backwards compatibility problem for 3.5 hosts with port 443 blocked

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#370]
This command:
pscheduler task throughput --dest sacr-pt1.es.net --source nettest.boulder.noaa.gov

always tries to run iperf3, when it should be running bwctliperf3.

It might already be fixed, but just in case not, creating a issue to track it.

Note from Andy on this:

I think I figured out the discrepancy between hosts that pick the wrong tool and hosts that don't. there are definitely some that seem to work 100% time and some that seem to pick the wrong tool 100% of the time. the ones that pick the wrong tool are ones that timeout after 5 seconds when trying to connect to the pscheduler port (probably because they have a firewall in place) vs ones that don't have a firewall and immediately give a fail to connect.  Mark's changes should help, but I'm gonna double check that when the scheduler calls "can-run" its not giving it 5 seconds to return or similar since otherwise the entire command will timeout everytime and pscheduler will move on to the next tool.

**Comment by mfeit-internet2** [comment]
187dbb5 should mitigate this to some degree.  The code that calls `can-run` now gives it five seconds to complete.  The functions being called by the `can-run` methods are given three to check each service, with the checks being done in parallel.  The `can-run` calls are still being done serially, so if a lot of them get jammed up, the process of picking a tool could take awhile.

`<rant>`

As I said during one of the calls this week, none of this stuff was ever intended to do anything other than a quick computation of the output based on the input.  The result of `can-run` is an indication of whether or not a tool plugin is capable of running a test as specified, not whether it will succeed or fail because of external conditions which may change between submission and run.

When doing backward compatibility was first proposed last year, I thought we made it clear that it would be a stopgap to ease the transition into 4.0, that it would be imperfect and that the limitations would be encouragement to upgrade.

I'm dragging my feet on #364 because it codifies a hack into an interface with a lifespan that extends well beyond dropping support for BWCTL.  I don't want someone to look at the plugin interface a decade from now and wonder what kind of crack we were smoking when we decided to push inside information across an interface that shouldn't have it.

The environment-variable hack is a lot cleaner and easier to remove.  If I need to do the same thing for `can-run` that was done for `participants`, I have no problem with that.

`</rant>`

**Comment by mfeit-internet2** [comment]
Agreed on:
 * Continue using the environment.
 * Make sure pass of variable is isolated.

**Comment by arlake228** [comment]
I see the issue here, super-easy fix but multiple ways we can tackle it. The crux of the issue is that the timeout in can-run to check for the services is 3 seconds, but the can-run process is only getting 2 seconds of timeout based on how `pscheduler.run_program()` is invoked by `pscheduler_internal`. The reason its only giving 2 seconds is here: https://github.com/perfsonar/pscheduler/blob/187dbb509b6f47b61a6e995b48c45949514b3d9e/pscheduler-server/pscheduler-server/database/external_program.sql#L41

The `short` parameter is always set to `True`, which in turn makes the timeout two seconds. This seems like maybe unintentional since the SQL function takes a timeout parameter, which is essentially always ignored.

Anyways, there are a few ways to fix it:

1. Decrease the timeout of the service checks from 3 seconds to 1 second, which should keep it within 2 seconds but will also increase the risk of false negatives.

2. Increase the timeout of can-run to something like 5 seconds which requires doing something about how the _short_ parameter is handled (i.e. don't pass it in pscheduler_internal, or pass it but override it if timeout is also set, etc)

**Comment by mfeit-internet2** [comment]
Deprecate `short` and get rid of anything that uses it.

**Comment by arlake228** [comment]
Confirmed that this fixed the issue. Command that was broken but now works: `pscheduler task throughput --dest antg-staging.es.net --source nettest.boulder.noaa.gov`
