### ISSUE TITLE
Misleading error message when malformed parameter

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#408]
After having solved the dependency issue in #406, we find that the error message given by pscheduler when the format/value of the `--timeout` parameter is not correct is a bit misleading and not helpful to the user:

```
pscheduler task --debug clock --timeout 30 --dest ps-d8.eshango.net
2017-04-13T13:05:52 Debug signal ignored; already not debugging
2017-04-13T13:05:52 Debug discontinued
2017-04-13T13:05:52 Assistance is from localhost
2017-04-13T13:05:52 Using slip of PT5M
2017-04-13T13:05:52 Converting to spec via https://localhost/pscheduler/tests/clock/spec
Submitting task...
2017-04-13T13:05:53 Fetching participant list
2017-04-13T13:05:53 Spec is: {"dest": "ps-d8.eshango.net", "timeout": "30", "schema": 1}
Unable to determine the lead participant: At /timeout: u'30' does not match '^(R\\d*\\/)?P(?:\\d+(?:\\.\\d+)?W)?(?:\\d+(?:\\.\\d+)?D)?(?:T(?:\\d+(?:\\.\\d+)?H)?(?:\\d+(?:\\.\\d+)?M)?(?:\\d+(?:\\.\\d+)?S)?)?$'
```

`pscheduler task --debug clock --timeout PT30S --dest ps-d8.eshango.net` works fine.

**Comment by mfeit-internet2** [comment]
The message is technically correct because the value of `timeout` is an ISO 8601 duration (e.g., `PT30S`), and integers aren't acceptable.

I agree that the message isn't helpful, but it is what the JSON Schema validator produces.  There have been proposals for new fields to specify 

I'll have to look at the error handler in our validator and see if I can make it pluck a non-standard field out of the JSON schema and use that as an error message.

Notes for later:

 * http://python-jsonschema.readthedocs.io/en/latest/errors/
 * https://github.com/geraintluff/tv4/issues/115

**Comment by mfeit-internet2** [comment]
Turns out that fixing this was as easy as experimenting with it.  I have an implementation for this stashed and will commit it as soon as we unfreeze the code.

Short summary:

Setting `x-invalid-message` in the definition of the type will use that string for the message, substituting the invalid value for `%s`.  Ergo, a declaration like...
```
    "Duration": {
        "type": "string",                                                             
        "pattern": r'^(R\d*\/)?P(?:\d+(?:\.\d+)?W)?(?:\d+(?:\.\d+)?D)?(?:T(?:\d+(?:\.\d+)?H)?(?:\d+(?:\.\d+)?M)?(?:\d+(?:\.\d+)?S)?\
)?$',
        "x-invalid-message": "'%s' is not a valid ISO 8601 duration."
        }
```
...will result in an error that looks like this...
```
timeout: '30' is not a valid ISO 8601 duration.
```

I'll go through all of the JSON validation stuff and add messages where appropriate.
