### ISSUE TITLE
failures on esmond archiving with the documented example

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#424]
Hi guys,

I am trying to make pscheduler to work with the ma archiver from a file configuration. But it fails.
You will see in general the test succeeds.

Please also note there is anyway an **error in the syntax** of the Esmond archiver example. The line with the utl declaration should be ending with a comma. https://github.com/perfsonar/pscheduler/wiki/Archivers

```
[psps-test2-mgmt ~]# pscheduler task --debug --archive @/etc/perfsonar/ma/test-psma-gn-01-buc-ro.geant.net.json --bind 131.188.81.82 --assist test-rhps02.geant.net throughput --source-node test-rhps02.geant.net --source 62.40.123.106  --dest-node 131.188.81.82 --dest 131.188.81.85
2017-05-02T11:36:45 Debug signal ignored; already not debugging
2017-05-02T11:36:45 Debug discontinued
2017-05-02T11:36:45 Assistance is from test-rhps02.geant.net
2017-05-02T11:36:45 Using slip of PT5M
2017-05-02T11:36:45 Converting to spec via https://test-rhps02.geant.net/pscheduler/tests/throughput/spec
Submitting with assistance from test-rhps02.geant.net...
2017-05-02T11:36:46 Fetching participant list
2017-05-02T11:36:46 Spec is: {"dest": "131.188.81.85", "source": "62.40.123.106", "source-node": "test-rhps02.geant.net", "dest-node": "131.188.81.82", "schema": 1}
2017-05-02T11:36:47 Got participants: {u'participants': [u'test-rhps02.geant.net', u'131.188.81.82']}
2017-05-02T11:36:47 Lead is test-rhps02.geant.net
2017-05-02T11:36:47 Pinging https://test-rhps02.geant.net/pscheduler/
2017-05-02T11:36:47 test-rhps02.geant.net is up
2017-05-02T11:36:47 Posting task to https://test-rhps02.geant.net/pscheduler/tasks
2017-05-02T11:36:47 Data is {"test": {"type": "throughput", "spec": {"dest": "131.188.81.85", "source": "62.40.123.106", "source-node": "test-rhps02.geant.net", "dest-node": "131.188.81.82", "schema": 1}}, "schedule": {"slip": "PT5M"}, "archives": [{"archiver": "esmond", "data": {"url": "https://test-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/", "measurement-agent": "GEANT_cli_archiver", "_auth-token": "4e0fd3e413b17678e47c05e9a94d277b36407acf", "retry-policy": [{"attempts": 1, "wait": "PT60S"}, {"attempts": 2, "wait": "PT600S"}, {"attempts": 11, "wait": "PT3600S"}]}}], "schema": 1}
Unable to post task: Invalid data for archiver "esmond"
```
```
[psps-test2-mgmt ~]# pscheduler task --bind 131.188.81.82 --assist test-rhps02.geant.net throughput --source-node test-rhps02.geant.net --source 62.40.123.106  --dest-node 131.188.81.82 --dest 131.188.81.85
Submitting with assistance from test-rhps02.geant.net...
Task URL:
https://test-rhps02.geant.net/pscheduler/tasks/34fea2cd-85f8-42e8-a441-1a68b7fe2999
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:
https://test-rhps02.geant.net/pscheduler/tasks/34fea2cd-85f8-42e8-a441-1a68b7fe2999/runs/24725100-92b1-4d42-8dc7-238e5cc931ab
Starts 2017-05-02T09:37:45Z (~5 seconds)
Ends   2017-05-02T09:38:04Z (~18 seconds)
Waiting for result...

* Stream ID 4
Interval       Throughput     Retransmits    Current Window
0.0 - 1.0      18.80 Mbps     0              244.71 KBytes
1.0 - 2.0      19.92 Mbps     0              302.63 KBytes
2.0 - 3.0      19.92 Mbps     0              325.80 KBytes
3.0 - 4.0      19.92 Mbps     0              328.70 KBytes
4.0 - 5.0      19.92 Mbps     0              328.70 KBytes
5.0 - 6.0      19.92 Mbps     0              328.70 KBytes
6.0 - 7.0      19.92 Mbps     0              328.70 KBytes
7.0 - 8.0      19.92 Mbps     0              328.70 KBytes
8.0 - 9.0      19.92 Mbps     0              328.70 KBytes
9.0 - 10.0     19.92 Mbps     0              328.70 KBytes

Summary
Interval       Throughput     Retransmits
0.0 - 10.0     19.81 Mbps     0

No further runs scheduled.

**Comment by mfeit-internet2** [comment]
Typo in wiki has been fixed.

**Comment by arlake228** [comment]
measurement-agent must always be an IP address. I can look into why that
error message is not passed up, but that is one thinG i notice righ away
that is problematic with your archiver spec.


On May 2, 2017 at 5:45:00 AM, Ivan Garnizov (notifications@github.com)
wrote:

Hi guys,

I am trying to make pscheduler to work with the ma archiver from a file
configuration. But it fails.
You will see in general the test succeeds.

Please also note there is anyway an *error in the syntax* of the Esmond
archiver example. The line with the utl declaration should be ending with a
comma. https://github.com/perfsonar/pscheduler/wiki/Archivers

[psps-test2-mgmt ~]# pscheduler task --debug --archive
@/etc/perfsonar/ma/test-psma-gn-01-buc-ro.geant.net.json --bind
131.188.81.82 --assist test-rhps02.geant.net throughput --source-node
test-rhps02.geant.net --source 62.40.123.106  --dest-node
131.188.81.82 --dest 131.188.81.85
2017-05-02T11:36:45 Debug signal ignored; already not debugging
2017-05-02T11:36:45 Debug discontinued
2017-05-02T11:36:45 Assistance is from test-rhps02.geant.net
2017-05-02T11:36:45 Using slip of PT5M
2017-05-02T11:36:45 Converting to spec via
https://test-rhps02.geant.net/pscheduler/tests/throughput/spec
Submitting with assistance from test-rhps02.geant.net...
2017-05-02T11:36:46 Fetching participant list
2017-05-02T11:36:46 Spec is: {"dest": "131.188.81.85", "source":
"62.40.123.106", "source-node": "test-rhps02.geant.net", "dest-node":
"131.188.81.82", "schema": 1}
2017-05-02T11:36:47 Got participants: {u'participants':
[u'test-rhps02.geant.net', u'131.188.81.82']}
2017-05-02T11:36:47 Lead is test-rhps02.geant.net
2017-05-02T11:36:47 Pinging https://test-rhps02.geant.net/pscheduler/
2017-05-02T11:36:47
<https://test-rhps02.geant.net/pscheduler/2017-05-02T11:36:47>
test-rhps02.geant.net is up
2017-05-02T11:36:47 Posting task to
https://test-rhps02.geant.net/pscheduler/tasks
2017-05-02T11:36:47
<https://test-rhps02.geant.net/pscheduler/tasks2017-05-02T11:36:47>
Data is {"test": {"type": "throughput", "spec": {"dest":
"131.188.81.85", "source": "62.40.123.106", "source-node":
"test-rhps02.geant.net", "dest-node": "131.188.81.82", "schema": 1}},
"schedule": {"slip": "PT5M"}, "archives": [{"archiver": "esmond",
"data": {"url":
"https://test-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/",
"measurement-agent": "GEANT_cli_archiver", "_auth-token":
"4e0fd3e413b17678e47c05e9a94d277b36407acf", "retry-policy":
[{"attempts": 1, "wait": "PT60S"}, {"attempts": 2, "wait": "PT600S"},
{"attempts": 11, "wait": "PT3600S"}]}}], "schema": 1}
Unable to post task: Invalid data for archiver "esmond"

[psps-test2-mgmt ~]# pscheduler task --bind 131.188.81.82 --assist
test-rhps02.geant.net throughput --source-node test-rhps02.geant.net
--source 62.40.123.106  --dest-node 131.188.81.82 --dest 131.188.81.85
Submitting with assistance from test-rhps02.geant.net...
Task URL:https://test-rhps02.geant.net/pscheduler/tasks/34fea2cd-85f8-42e8-a441-1a68b7fe2999
Running with tool 'iperf3'
Fetching first run...

Next scheduled run:https://test-rhps02.geant.net/pscheduler/tasks/34fea2cd-85f8-42e8-a441-1a68b7fe2999/runs/24725100-92b1-4d42-8dc7-238e5cc931ab
Starts 2017-05-02T09:37:45Z (~5 seconds)
Ends   2017-05-02T09:38:04Z (~18 seconds)
Waiting for result...

* Stream ID 4
Interval       Throughput     Retransmits    Current Window
0.0 - 1.0      18.80 Mbps     0              244.71 KBytes
1.0 - 2.0      19.92 Mbps     0              302.63 KBytes
2.0 - 3.0      19.92 Mbps     0              325.80 KBytes
3.0 - 4.0      19.92 Mbps     0              328.70 KBytes
4.0 - 5.0      19.92 Mbps     0              328.70 KBytes
5.0 - 6.0      19.92 Mbps     0              328.70 KBytes
6.0 - 7.0      19.92 Mbps     0              328.70 KBytes
7.0 - 8.0      19.92 Mbps     0              328.70 KBytes
8.0 - 9.0      19.92 Mbps     0              328.70 KBytes
9.0 - 10.0     19.92 Mbps     0              328.70 KBytes

Summary
Interval       Throughput     Retransmits
0.0 - 10.0     19.81 Mbps     0

No further runs scheduled.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/perfsonar/pscheduler/issues/424>, or mute the thread

**Comment by mfeit-internet2** [comment]
```
{
        "_auth-token": "4e0fd3e413b17678e47c05e9a94d277b36407acf",
        "measurement-agent": "GEANT_cli_archiver",
        "retry-policy": [ ... ],
        "url": "https://test-psma-gn-01-buc-ro.geant.net/esmond/perfsonar/archive/"
    }
```

The `measurement-agent` is of type `Host`, which has to be either an IP address or a valid (but not necessarily resolvable) DNS host name.  Underscores aren't valid in host names.
