### ISSUE TITLE
ability to run pscheduler on a user defined port

### ISSUE THREAD

**Issue by bltierney** [perfsonar/pscheduler#426]
Many DOE labs have requested the option to run pscheduler on a port other than 443.

Perhaps this is just a documentation issue, or perhaps there is coding / config file work needed too?

**Comment by mfeit-internet2** [comment]
This could be done by allowing tests with `host` or `{source,dest}-node` options to accept an optional colon and port (e.g.,  `foo.example.org:4443`).  In order to use an alternate port, these options will be required.

To make this happen:

- [ ] The web server to be reconfigurable to use an alternate port.  Since pScheduler just adds a new location to the server configuration, this is the toolkit's problem.

- [ ] The API will need to make sure that any URL it returns includes the port in the original request.  This should be okay because everything returns the base URL from the request.

- [ ] The `task` command's assist feature will have to accept a port number.  Explicit use of this feature (`--assist` switch or `$PSCHEDULER_ASSIST`) will be required if the server is on an alternate port.  Might be able to find a way to find out what port was used.  (Perhaps listening on 127.0.0.1:443 will eliminate the need for this.)

- [ ] Test spec validators must be changed to accept the new format for the node-related options.  Currently, this is `pScheduler/Host`.  Maybe call the new one `NetLocation`.  This will need to handle IPv6 addresses with ports per RFC 2732 (e.g., `[dead:beef::bad:cafe]:4443`).

- [ ] All test packages will have to depend on pscheduler-server >= 1.1 (or whatever version it ends up in) and pscheduler-server will need to depend on python-pscheduler >= 1.1.  Same for pscheduler-core (for the assist feature in `task`).

- [ ] We will need to document and educate users that the lead participant will require this upgrade for it to work.


I'm going to leave this slated for 1.0.1 but don't guarantee it will happen in that release.

**Comment by mfeit-internet2** [comment]
On reflection, this may just require making everything accept netlocs in host[:port] format and making the validators accept it.  Might be easy.

**Comment by mfeit-internet2** [comment]
I'd like to leave it open for QA, and I also need to do the version dependency thing discussed above, which I missed before pulling.

**Comment by mfeit-internet2** [comment]
I think I'm good with this.  Closing.

**Comment by dimm0** [comment]
How can I set the non-standard port for pscheduler?

If I set the port in group members in meshconfig json, like:

     {
         "members" : {
            "members" : [
               "ip1:8443",
               "ip2:8443",
                .....
            ],
            "type" : "mesh"
         },

Then I get the error:

[root@testpoint-zbsxh /]# cat /var/log/perfsonar/*
2017/10/12 01:25:53 (9) ERROR> Agent.pm:352 perfSONAR_PS::MeshConfig::Agent::__configure_host - Can't find any host blocks associated with the addresses on this machine: 127.0.0.1, 0:0:0:0:0:0:0:1, testpoint-zbsxh, localhost, 10.244.12.4
