### ISSUE TITLE
Improve Affinity Handling for Unroutable Addresses

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/pscheduler#493]
The [code in iperf3's run method](https://github.com/perfsonar/pscheduler/blob/master/pscheduler-tool-iperf3/iperf3/run#L312) doesn't handle `(None, None)` being returned by `address_interface()` and will pass it through to `interface_affinity()`, which uses it blindly.

**Comment by daldoyle** [comment]
This was fixed in both iperf3 and nuttcp tools with a simple "if interface:" before the affinity lookup. I think ultimately this is a sort of config error since it was originally reported by bltierney when network manager had sent localhost to 127.0.1.1 which no interface had, but better to fix it up than have it crash.
