### ISSUE TITLE
update the archiver url and credentials of tasks in the pipe of the scheduler

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#525]
Hi Mark, guys,

Here I am looking for a command on CLI, which will me to replace a specific MA url with another one including the credentials.

IMHO 24h is quite a period to wait for updates of the MA url to propagate from meshconfig.
Use case is emergency cases, where the configured MA is unavailable.

Please also consider the ability to update tasks, that have passed, but are still not archived for the reason of whatever issues.

Regards,
Ivan

**Comment by arlake228** [comment]
You don't have to wait 24 hours anymore. That was fixed awhile back. A new
task will be created within a few minutes of the change to the URL or
credentials. Also, if this is not the behavior you think you are seeing,
it's a mesh-config not a pscheduler issue.

**Comment by mfeit-internet2** [comment]
Changing the archivers after the fact isn't something I really thing should be added to pScheduler.

You have a couple of options to do a seamless key transition:

If the MA can be configured with multiple authentication keys:
1.  Add a second key to the MA
1.  Change the mesh configuration to use the new key.
1.  Wait out the longest archiving TTL you have configured in the mesh
1.  Remove the old key from the MA

Otherwise, you can do it entirely within perfSONAR:
1.  Add a second archiver to your tests with the new key.
1.  Wait at least the TTL being specified in your tasks for tasks with the old key to be archived or expire.
1.  Change the key on the MA.
1.  Remove the archiver with the old key from your tests.

The down side here is that for the six hours in the second step, your pScheduler machines will have twice the archiving load on them.  This will be less of a problem once we do streaming archivers (4.0.2 if I have anything to say about it).
