### ISSUE TITLE
Latency tests with LNS need 2 contexts

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#565]
Similarly to #560 I think latency tests need to check if they're given 2 contexts.

This fails:
```
antoine^2@central:)~$ pscheduler task --context '{ "schema": 1, "contexts": [ [ { "context": "linuxnns", "data": { "namespace":"vpn1-2" } } ] ] }' latency --source-node mp1 --dest 10.0.0.1
pscheduler task --context '{ "schema": 1, "contexts": [ [ { "context": "linuxnns", "data": { "namespace":"vpn1-2" } } ], [ { "context": "linuxnns", "data": { "namespace":"vpn2-1" } } ] ] }' latency --source-node mp1 --dest 10.0.0.1 --dest-node mp2
Submitting task...
Unable to post task: Number of contexts for this task must be exactly 1
```

But this fails too (as one would imagine, because we need 2 contexts for this task):
```
antoine^2@central:)~$ pscheduler task --context '{ "schema": 1, "contexts": [ [ { "context": "linuxnns", "data": { "namespace":"vpn1-2" } } ] ] }' rtt --source-node mp1 --dest 10.0.0.1                                                                                                                                                                      pscheduler task --context '{ "schema": 1, "contexts": [ [ { "context": "linuxnns", "data": { "namespace":"vpn1-2" } } ] ] }' latency --source-node mp1 --dest 10.0.0.1
Submitting task...
Task URL:
https://mp1/pscheduler/tasks/ef03a8b3-bd7a-42d4-b5fc-c0ce8591ec39
Running with tool 'owping'
Fetching first run...

Next scheduled run:
https://mp1/pscheduler/tasks/ef03a8b3-bd7a-42d4-b5fc-c0ce8591ec39/runs/579c19d4-14d2-49b0-be82-9e9e1b411993
Starts 2017-11-13T15:47:55+01:00 (~8 seconds)
Ends   2017-11-13T15:48:16+01:00 (~20 seconds)
Waiting for result...

Run failed.  The following errors were reported:
By mp1:
    owping returned an error: owping: FILE=owping.c, LINE=1602, Unable to open control connection to [10.0.0.1]:861.

No runs scheduled for this task.
```

**Comment by tonin** [comment]
And maybe then a question comes (thinking about your use cases @igarny): do we want the OWAMP control connection to be in the measured VPN or in the out of band pScheduler network?

**Comment by mfeit-internet2** [comment]
So about that...

The philosophy behind pScheduler was (and still is) that any process required to complete a test be started by a tool's run method and stopped when the test is done.  For throughput, the target tools (iperf2, iperf3 and nuttcp) all  fit the program-on-both-ends model, and that was designed two-participant.  For RTT, any host with enough network stack to run pScheduler is going to return ICMP echos without requiring a server process anyway.  That test was designed single-participant so any pingable host could be tested.

Latency could have been done on the same model as throughput: one end runs owampd, the other runs owping and both get torn down at the end.  Having to support owstream ruled that out because there wasn't (and still isn't) a way to dole out ports for the server processes.  Based on what people seem to be doing, you'd need lots of them.  So for that, the model became that every perfSONAR node has an owampd running that serves as the far end for everything.  So, like RTT, we did it single-participant.

The status quo is a mixed blessing.  On one hand, we can test to any OWAMP (or TWAMP in the future) server whether or not there's perfSONAR on the other end and any number of powstreams can test to the same owampd.  But it does mean there's one owampd and, isn't under pScheduler's control and it isn't listening in the alternate namespaces.

Once we have resource management, one-shot latency measurements with a short-lived owampd will become possible and would work the same way as, say, iperf.  We'd have to evolve the test schema a bit to make two-participant tests work, but I don't have any objection to that and it won't be difficult.

That still doesn't fix powstream, which expects an always-on owampd.  There are two ways to make owampd available in the alternate namespaces:

 * Run one owampd per namespace.  Since the round figure Ivan gave me for how many VPNs there could be per host was "hundreds,"  this is not going to be practical.

 * Find a way to bridge the in-namespace interface to the root-namespace interface so the root's owampd will be able to service anything in another namespace.  I was thinking there might be something that could be done with iptables or the interface mechanism so it would work.  This is straight Linux administration job, so someone other than me could explore those avenues. 

Not a great answer, but that's what the answer is for the time being.

**Comment by igarny** [comment]
Hi Mark,

Thanks for the explanation.
Indeed we need to consider the implementation of the performance measurement tools based on the requirements they impose and the features available from the kernel and IP stack.
IMHO it is a not a good assumption, that a OWAMP is always available. And there are direct use cases where latency is not allowed on specific interfaces.
Since OWAMP is not part of the IP stack, it would be nice to have a way to control the creation and disposal of the OWAMP daemon for a specific test.
I hope it is acceptable to have a procedure, which verifies there are no latencybg tasks running before running or destroying the owampd process. So that we are able reapply the process for throughput tests and combine it for latencybg tests.

Thanks

**Comment by tonin** [comment]
Thank you for these explanations @mfeit-internet2. My assumption was wrong, I now know that latency is currently a pScheduler single participant test. Maybe we should add some documentation to the [pScheduler Test and Tool reference page](http://docs.perfsonar.net/pscheduler_ref_tests_tools.html) that explain the difference between single and 2 participants tests and list the test types accordingly?

And then I guess I can crate a new issue for future development of pScheduler support for 2 participants latency measurements (that will depend on pScheduler resources management).  Or do we already have that somewhere?

**Comment by tonin** [comment]
This is not a bug.  See the above linked issues for follow up.
