### ISSUE TITLE
pscheduler troubleshoot doesn't check for running archiver

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#568]
It would be good to have `pscheduler troubleshoot` test if the pscheduler-archiver is running (and possibly try storing results).

```
antoine@mp02:)~$ pscheduler troubleshoot
Performing basic troubleshooting of localhost.

Checking for pScheduler on localhost... OK.
Idle test on localhost.... 9 seconds.... OK.

pScheduler appears to be functioning normally.
antoine@mp02:)~$ sudo service pscheduler-archiver stop
antoine@mp02:)~$ ps aux | grep archiver
antoine   1284  0.0  0.0  12944   992 pts/0    R+   12:07   0:00 grep --color=auto archiver
antoine@mp02:)~$ pscheduler troubleshoot
Performing basic troubleshooting of localhost.

Checking for pScheduler on localhost... OK.
Idle test on localhost.... 9 seconds.... OK.

pScheduler appears to be functioning normally.
```

**Comment by mfeit-internet2** [comment]
This has been added:

```
% pscheduler troubleshoot
Performing basic troubleshooting of localhost.

Checking for pScheduler on localhost... OK.
Idle test on localhost.... 9 seconds.... Checking archiving... OK.

pScheduler appears to be functioning normally.
```

Because there's no guarantee that, say, esmond is running on a given host or to know how authentication should be configured, what's tested is a pair of archivings based on specs for the bitbucket and failer archivers.  These are guaranteed to work anywhere and have no side effects.

On a related note, there were some discussions about having a way to send notifications when there are run or archiving failures; we may have a ticket open on that.

**Comment by tonin** [comment]
Thanks, that will be useful.  We run into a few pscheduler-archivers being down in our current Jisc training.  Not sure why they suddenly stopped though...
