### ISSUE TITLE
pscheduler result: "Data returned from the server doesn't look like a run result."

### ISSUE THREAD

**Issue by candlerb** [perfsonar/pscheduler#692]
I ran a third-party repeated test like this, using abbreviated hostnames:

```
$ pscheduler task --max-runs 5 --repeat PT1M throughput --source wrn-perf1 --dest ix-perf1
Submitting task...
Task URL:
https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3bd69
Running with tool 'iperf3'
Fetching first run...
```

It all ran fine to conclusion, showing the results as it went.

But if I use the Task URL to try and re-retrieve the results, this is what I get:

```
$ pscheduler result --diags https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3bd69
Data returned from the server doesn't look like a run result.
$ 
```

That's not a very helpful error message.

If I trim a few characters off the URL, I get a different error:

```
$ pscheduler result --diags https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3b
Resource Not found.
```

That suggests it's talking to the server correctly (and the fact that the https certificates aren't valid doesn't matter)

Here's the actual data being returned at the original URL:

```
$ curl -k https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3bd69
{"test": {"type": "throughput", "spec": {"dest": "ix-perf1", "source": "wrn-perf1", "schema": 1}}, "tool": "iperf3", "schema": 1, "schedule": {"repeat": "PT1M", "max-runs": 5, "slip": "PT5M"}}
```

**Comment by candlerb** [comment]
(BTW I am using ps toolkit 4.0.2.2, so maybe this is different in 4.1)

As far as I can see, this URL is suitable for use with `pscheduler watch`, but not after the job has terminated.

```
$ pscheduler watch https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3bd69
No runs scheduled for this task.
```

If I start a new one:

```
$ pscheduler task --url --max-runs 5 --repeat PT1M throughput --source wrn-perf1 --dest ix-perf1
https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7
$ pscheduler watch https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7
No runs scheduled for this task.
```

But then retry after a few seconds:

```
$ pscheduler watch https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7

Next scheduled run:
https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7/runs/7cdcc906-e3b2-4b59-b139-f3bfa8afea0d
Starts 2018-10-06T13:29:32Z (~14 seconds)
Ends   2018-10-06T13:29:51Z (~18 seconds)
```

However this only shows me the remaining runs as they occur, not the ones which have already occured.

**Comment by mfeit-internet2** [comment]
On the first item:
```
$ pscheduler result --diags https://wrn-perf1/pscheduler/tasks/e75e8210-6ff2-426a-a281-9e0c69f3bd69
Data returned from the server doesn't look like a run result.
```

What's going on here is a task URL being given to the `result` command, which expects a URL that points to the result of a run.  (Tasks are separate entities from their runs, of which there can be more than one.)  Because you can put any URL (which is intentional), all `result` cares about is that the data looks right.

It wouldn't be difficult to enhance `result` to recognize when the data returned is a task, have it dig up the list of runs and dump results for each.  I'll take that as an action item for this ticket.

In the short term, this bit of shell script will use a task URL to do the equivalent:
```
#!/bin/sh -e                                                                                                                        

TASK_HREF="$1"

RUNS_HREF=$(curl -s -k "${TASK_HREF}?detail" | jq -r '.detail."runs-href"')

echo "Runs from ${TASK_HREF}:"
for RUN_HREF in $(curl -s -k "${RUNS_HREF}" | jq -r '.[]')
do
    echo
    pscheduler result "${RUN_HREF}"
done

```
-----
On the second item:

```
$ pscheduler task --url --max-runs 5 --repeat PT1M throughput --source wrn-perf1 --dest ix-perf1
https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7
$ pscheduler watch https://wrn-perf1/pscheduler/tasks/ea393075-1383-49b2-976b-488a1e1b51a7
No runs scheduled for this task.
```

The `watch` command is intended as a way to re-attach to a long-running task and see the results as they happen.  There will be some delay between the time the task is submitted and the first runs being scheduled, which is what you're seeing there.  The `task` command's default behavior is to wait for the first run to be scheduled and then run `watch` to wait for and show the results.  From a practical standpoint, there isn't a lot of reason to run `task --url` and then run `watch` immediately afterward since the same information is displayed as things progress.

**Comment by mfeit-internet2** [comment]
This has been done and will appear in the 4.1.6 release.
