### ISSUE TITLE
Trace tools set dest as lead participant if source is not reachable

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#725]
I'll start off by saying this is an artifact of the bwctl backward compatibility. Take the output below as an example:

```
# pscheduler task trace --source 154.114.10.164 --dest 141.211.176.232
Submitting task...
Task URL:
https://141.211.176.232/pscheduler/tasks/91889aa3-f5d0-4041-8d32-a1829b1094ae
Running with tool 'traceroute'
Fetching first run...

Next scheduled run:
https://141.211.176.232/pscheduler/tasks/91889aa3-f5d0-4041-8d32-a1829b1094ae/runs/b91e810e-9fd3-4640-948b-5a7b440308f9
Starts 2018-11-30T20:34:31Z (~7 seconds)
Ends   2018-11-30T20:34:39Z (~7 seconds)
Waiting for result...

Run failed.

Limit system diagnostics:
  Hints:
    requester: 198.128.151.25
    server: 141.211.176.232
  Identified as everybody
  Classified as everybody, default
  Application: Defaults
    Group 1: Limit 'innocuous-tests' passed
    Group 1: Limit 'rtt-default' failed: Test is not 'rtt'
    Group 1: Limit 'throughput-default' failed: Test is not 'throughput'
    Group 1: Want any, 1/3 passed, 2/3 failed: PASS
    Application PASSES
  Proposal meets limits


Diagnostics from 141.211.176.232:
    traceroute -q 1 -4 -s 154.114.10.164 -N 30 -n 141.211.176.232

Error from 141.211.176.232:
    
    bind: Cannot assign requested address
    

No further runs scheduled.
```

Note that the `dest` is set as the lead which is incorrect and leads to an incorrect attempt to bind on the `dest` host using the `source` address. The problem is that the `trace`test's `participants` call returns only one participant  and the `traceroute` tool does not short-circuit in `can-run` if there is only 1 participant. The reason it does not short-circuit is that it expects `bwctltraceroute` with a higher tool priority to handle any one participant cases. Since `bwctltraceroute` is not installed by default anymore, tests like this make there way to the trace tool. 

We need to discuss whether we think we should check the participants in the tools, or if we we should wait until BWTL support is dropped in February at which point we should update `participants` to always return two participants.

**Comment by mfeit-internet2** [comment]
This is definitely a problem with the `participants` method.  The code in question is part of the BWCTLBC hack:
```
if source is None or has[source]["pscheduler"]:
    participants = [ source ]
elif has[destination]["pscheduler"]:
    participants = [ destination ]
else:
    #if backward compatibility hacks failed, proceed normally
    participants = [ source ]
```
I can't see any case where returning the destination as a first participant in a `trace` would begin to make sense, and I think this code is flat wrong.  Bwctltraceroute's `can-run` looks only at the source.  It checks for pScheduler and bows out if it's there and then checks for BWCTL and accepts if that's present.  We could fix this in 4.1.5 easily even if we are going to tear it all out in 4.2.

Since neither `participants` nor `can-run` is supposed to be reaching out and touching anything, all of that goes away in February, which can't come soon enough.  :-)

Trace is and always should be a one-participant tool, just like RTT, because there is no need to coordinate with pScheduler at the other end.  The participant list is derived from the test spec; the tools see the latter but not the former for architectural reasons (tools aren't supposed to know) and because they'd essentially be doing checks for programming mistakes in the test plugins.
