### ISSUE TITLE
Chrony does not expose time sync information through API for programs ( pscheduler )

### ISSUE THREAD

**Issue by igarny** [perfsonar/pscheduler#857]
Hello Mark,

Unfortunately for GEANT Ops, pscheduler ignores the operation of the Chrony service on their servers, which leads to invalid statements in the pscheduler measurements: 

    "clock-survey": [
        {
            "error": "No response received from 127.0.0.1.",
            "synchronized": false,
            "time": "2019-06-03T09:26:25.152698+00:00"
        },
        {
            "error": "No response received from 127.0.0.1.",
            "synchronized": false,
            "time": "2019-06-03T10:26:25.254677+01:00"
        }
    ],

This in general is not a blocker, since I can see measurements running, but is nevertheless a miss.
Still I can't be absolutely sure there is no side negative impact in the operation pscheduler.

Here are some facts from current pS 4.2 snapshot:
```
ivan@psU-71-74:~$ chronyc sources
210 Number of sources = 8
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^+ ntp0.rrze.uni-erlangen.de     1   6    77    11    +73us[  +73us] +/- 1369us
^+ ntp1.rrze.uni-erlangen.de     1   6    37    11  +1000ns[+1000ns] +/- 1249us
^* ntp2.rrze.uni-erlangen.de     1   6    37    12    +18us[  -38us] +/- 1251us
^+ ntp3.rrze.uni-erlangen.de     1   6    37    12   -136us[ -136us] +/- 1175us
^- ts1.sct.de                    2   6    17    16  +1288us[+1242us] +/-   32ms
^- 2a01:4f8:c17:b8f::2           2   6    17    16   +850us[ +804us] +/-   37ms
^- mail.lafkor.de                2   6    17    16  -1714us[-1838us] +/-   64ms
^- 2a03:b0c0:3:e0::258:9001      2   6    17    15  +1656us[+1610us] +/-   32ms
```
```
ivan@psU-71-74:~$ chronyc sourcestats
210 Number of sources = 8
Name/IP Address            NP  NR  Span  Frequency  Freq Skew  Offset  Std Dev
==============================================================================
ntp0.rrze.uni-erlangen.de   6   3    10     +3.340     17.001   +189us    16us
ntp1.rrze.uni-erlangen.de   5   4     8     +3.571     58.808   +123us    24us
ntp2.rrze.uni-erlangen.de   5   3     8     +2.891     16.077   +123us  7856ns
ntp3.rrze.uni-erlangen.de   5   5     8     +1.458     70.336    -97us    28us
ts1.sct.de                  4   3     7     +2.515    150.067  +1352us    17us
2a01:4f8:c17:b8f::2         4   4     7     -1.852    232.320   +761us    27us
mail.lafkor.de              4   3     6     +6.017   1378.933  -1448us   236us
2a03:b0c0:3:e0::258:9001    4   3     6     +9.618    391.297  +2000us    46us
```
```
ivan@psU-71-74:~$ dpkg -l pscheduler-server
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                      Version                   Architecture              Description
+++-=========================================-=========================-=========================-========================================================================================
ii  pscheduler-server                         1.1.6+20190322201018-1    all                       pScheduler server components
```

**Comment by mfeit-internet2** [comment]
The output is technically right because the only NTP implementation we support NTPD (see perfsonar/toolkit/issues/278 and perfsonar/toolkit/issues/308).

That doesn't mean pScheduler _can't_ support it, but there's a hurdle.  Chrony's sole API is the `chronyc` command-line program.  They don't provide an API for other programs to query it, which would leave us stuck running `chronyc` and picking the output apart.  (The C library has `ntp_adjtime()`, which is how the [code that figures it out for NTPD](https://github.com/perfsonar/pscheduler/blob/master/python-pscheduler/pscheduler/pscheduler/clockstate.py) gets its information.    Figuring out how to do the equivalent for Chrony would be a small standalone project if someone at GÉANT wants to figure it out.

As for the operational impacts of this:

pScheduler operates using the system clock, so if the clocks are within a second of each other (disciplined or not), there should be no problems.

When a run fails and a clock survey is triggered, the only important data is the time reported by both systems.  The other information is for the benefit of whoever's reading it.

**Comment by mfeit-internet2** [comment]
Newer versions of `chronyc` have a `-c` switch that produces CSV, which may make querying Chrony easier.

**Comment by mfeit-internet2** [comment]
**Release Notes:**

Added support for systems with clocks disciplined by Chrony rather than NTPD.

**Comment by mfeit-internet2** [comment]
Had some small concerns about the software not running quickly when chronyd wasn't up, but those were unfounded.  Looks okay.
