### ISSUE TITLE
Private archiver parameters

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#87]
Archivers by there very nature may sometimes require auth information or similar which should be kept private. For example, you can provide esmond with an authentication token it uses when registering results. Currently, all archiver fields get displayed in the REST API when you query a task. I propose that a field in the archiver "data" section starting with '_' (e.g. "_auth-token") get removed prior to display in the REST API. It would still get passed around internally just as any other parameter.

**Comment by mfeit-internet2** [comment]
That was easy.  Did this to archiver data and the test spec as well.

Instead of removing the fields, they're replaced with `null` to avoid having the JSON come up invalid because a required field is missing.  (The JSON validator will still have to accept a  `null` in those cases.)

Reassigning to you; close when you're happy that it works.

**Comment by arlake228** [comment]
Confirmed that it works, closing.
