### ISSUE TITLE
Can we run multiple throughput tests simultaneously?

### ISSUE THREAD

**Issue by bgrounds** [perfsonar/pscheduler#874]
My goal is measure jitter between every pair of hosts in a large, fully connected mesh.
Ideally, I'd like these measurements to run as close to continuously as possible.

As far as I can tell, it seems that the throughput test is the only one that will measure jitter, so that's what I'm using. If there's another kind of test that measures jitter, I'd be open to using it.

I currently have 21 perfsonar hosts in a fully connected mesh.
Each host is configured to run throughput tests using iperf3 with a low bandwidth udp stream.

It seems that pscheduler will not schedule multiple throughput tests at the same time.
This results in very sparse measurements for any particular pair of hosts.

It seems reasonable that pscheduler should be able to simultaneously start multiple throughput tests to different hosts - perhaps using different server ports for each host. I believe the `latencybg` tests work this way.

Is this possible?

If not, I'm also open to workarounds.

For example, I can imagine spinning up (N-1) iperf3 servers on different ports on each of the N servers in my fully connected mesh. Then I might configure each host to run (N-1) throughput tests, each using its own dedicated `--single-ended-port`.

I'm not sure if this example would be the most straight-forward way to achieve my goal. I'm also not sure if pscheduler would actually schedule the different `--single-ended` throughput tests at the same time - even though this should eliminate any port conflicts.

Any insights are appreciated.

Thanks!

**Comment by mfeit-internet2** [comment]
Throughput is (generally) a resource-heavy test and isn't scheduled concurrently because doing so would distort the results for all of them.

You can get a jitter figure by measuring latency and calculate it based on the statistics provided or have it dump the raw data on each packet and calculate it yourself.  I would recommend using the `latencybg` test, which will provide a continuous stream of measurements and run in the background in parallel with throughput when that runs.

Also, if there are other tools out there that will measure jitter (or other things), pScheduler is extensible and isn't limited to the rtt/latency/throughput/trace that BWCTL was.

BTW, this would be better on perfsonar-user than in the ticket system.  The tickets usually get read by the developers.
