### ISSUE TITLE
JSON passed to archiver plug-in missing result.test object

### ISSUE THREAD

**Issue by arlake228** [perfsonar/pscheduler#929]
@tonin noticed while setting up an HTTP and DNS that esmond archiving was failing with this error: No type set for raw record

Looking at code that happens when the Esmond archiver cannot find result.test.type in the JSON. Turning on debugging, indeed the entire result.test object was missing from the JSON passed to the archiver.

We had trouble recreating this on other hosts and none of the code involved had any obvious changes. We ran into it very close to the 4.2.1 release, so plan is to do a workaround in the esmond archiver that falls-back to result.task.test.type when result.test.type is not set. Will leave this issue open in case we are able to reproduce the problem more reliably.

**Comment by mfeit-internet2** [comment]
Discussion on this from Slack:

Andy Lake 10:45 AM
@mfeit debugging the archiver thing with antoine. it looks like the esmond archiver is looking for the test type in JSON that gets passed in under result.test.type but looking at the JSON it is setting the test type is under result.task.test.type. did something change in the format? also confused why we would not see this for all test types and anything running the esmond archiver (edited) 

Mark Feit 10:45 AM
Ugggg, I hope not.
Let me check the history.

Mark Feit 10:57 AM
Nothing in the archiver daemon changed.  Let me see if the runner changed something.

Andy Lake 11:22 AM
so fwiw i see the test defined under result and result.task on all my nodes (4.2.0, 4.2.1 and 4.3.0). if there's nothing obvious I could update the esmond archiver to look both places for now. i don't think the other archivers dig into the results like that. sounds like its maybe only happen some of the time for antoine (edited) 

Mark Feit 11:23 AM
Yeah, I'm not finding much, either.

Mark Feit 11:33 AM
You should still be able to find the task info in .result.test, which has been there since day one.  .result.run and .result.task were added as additional info in #683 for 4.2b1. (edited) 
So there's duplication, but only in the interest of not breaking existing uses.
There are no conditionals in the daemon that could make it be formatted in any other way.
I pulled the spec for one of the tasks that Antoine listed as showing an error, and there's no transform in it, so no pilot error.

**Comment by tonin** [comment]
Not sure if it helps, and not sure its a constant behavior, but it looks like it's mostly the tests coming from my mesh that fail archiving and not the one I run from the CLI with the same archiver definition.  Would there be any difference?

**Comment by mfeit-internet2** [comment]
@tonin  It would be interesting to retrieve the task spec from one in your mesh that fails and one from the CLI that doesn't and see where they differ.

**Comment by tonin** [comment]
The change from https://github.com/perfsonar/pscheduler/commit/3c2151bd7747a9da67ed61ceb7a2698fe8ded532 didn't solve this issue.  Hosts running 4.2.2 still show the same behavior.

However, this might be related to https://github.com/perfsonar/pscheduler/issues/941 and I'm now running a patch from https://github.com/perfsonar/pscheduler/commit/7a667b8a2b2b37eebe997d80d77395e3c5ba39f9 to confirm.

**Comment by tonin** [comment]
Running the above-mentioned patch on a host during a bit more than 24h and I don't see the raw record error anymore.  Seems this is fixed!
