### ISSUE TITLE
Old pscheduler powstream directories

### ISSUE THREAD

**Issue by tonin** [perfsonar/pscheduler#935]
Not sure if this is a bug or a feature request.  After running, some powstream session files are left in place in `/var/lib/pscheduler/tool/powstream` And these can be big.  On one of my testbed hosts, this directory is nearly 20 GB big.

On a production 4.2 (now 4.2.1) machine, I also see some months old directories still being kept.  Is there a reason for that?  Should we have a cronjob cleanup this space from time to time?

**Comment by arlake228** [comment]
The run command has some code that should be doing this. It looks like there must be some failure case where this is not happening. Looking at my ESnet hosts most of them look fine, but a couple seem to have more old data. Easy solution may be just to have a cron job that acts as a failsafe and cleans out data more than a few days old or something.

**Comment by tonin** [comment]
On the host where I see a lot of leftovers from powstream, all the old directories contain the `.powlock` file.  Shouldn't this file be cleared by powstream when it exits?  I'm trying to understand the reason why these directories are not getting discarded automatically…

**Comment by mfeit-internet2** [comment]
I have a more-general proposal for solving this:  instead of putting all of that housekeeping into each tool, let's shift responsibility for temporary space to the runner.

Before starting a plugin's `run` method, it would create a directory and set `$TMPDIR` to point at it.  At the conclusion of the run (successful or not), the directory is destroyed.  As a hedge against the runner crashing and leaving old files around, its first act on startup could be to wipe all of the temporary space clean.  At that point, it would be guaranteed that any remaining directories were left over from a prior run.

This would be trivial to implement and would mean that the plugins can use `mkstemp()` or anything else that honors `$TMPDIR`.

**Comment by mfeit-internet2** [comment]
Keep an eye on this once everything hits the test bed; close if we're good.

**Comment by mfeit-internet2** [comment]
I'm happy with this.  Closing.
